/* mozClient.c
   Generated by gSOAP 2.7.6e from comptax.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "mozH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) mozClient.c ver 2.7.6e 2007-02-01 08:00:53 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_moz1__pmConnect(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *password, char *database, char **key)
{	struct moz1__pmConnect soap_tmp_moz1__pmConnect;
	struct moz1__pmConnectResponse *soap_tmp_moz1__pmConnectResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_moz1__pmConnect.login = login;
	soap_tmp_moz1__pmConnect.password = password;
	soap_tmp_moz1__pmConnect.database = database;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_moz1__pmConnect(soap, &soap_tmp_moz1__pmConnect);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__pmConnect(soap, &soap_tmp_moz1__pmConnect, "moz1:pmConnect", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__pmConnect(soap, &soap_tmp_moz1__pmConnect, "moz1:pmConnect", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	*key = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_moz1__pmConnectResponse = soap_get_moz1__pmConnectResponse(soap, NULL, "moz1:pmConnectResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (key && soap_tmp_moz1__pmConnectResponse->key)
		*key = *soap_tmp_moz1__pmConnectResponse->key;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_moz1__pmFinish(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, unsigned int *result)
{	struct moz1__pmFinish soap_tmp_moz1__pmFinish;
	struct moz1__pmFinishResponse *soap_tmp_moz1__pmFinishResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_moz1__pmFinish.key = key;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_moz1__pmFinish(soap, &soap_tmp_moz1__pmFinish);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__pmFinish(soap, &soap_tmp_moz1__pmFinish, "moz1:pmFinish", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__pmFinish(soap, &soap_tmp_moz1__pmFinish, "moz1:pmFinish", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_unsignedInt(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_moz1__pmFinishResponse = soap_get_moz1__pmFinishResponse(soap, NULL, "moz1:pmFinishResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_moz1__pmFinishResponse->result)
		*result = *soap_tmp_moz1__pmFinishResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_moz1__Setup(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, struct moz1__SetupResponse *_param_1)
{	struct moz1__Setup soap_tmp_moz1__Setup;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_moz1__Setup.key = key;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_moz1__Setup(soap, &soap_tmp_moz1__Setup);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__Setup(soap, &soap_tmp_moz1__Setup, "moz1:Setup", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__Setup(soap, &soap_tmp_moz1__Setup, "moz1:Setup", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_moz1__SetupResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_moz1__SetupResponse(soap, _param_1, "moz1:SetupResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_moz1__Prepare(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *query, char *name, unsigned int arity, unsigned int *result)
{	struct moz1__Prepare soap_tmp_moz1__Prepare;
	struct moz1__PrepareResponse *soap_tmp_moz1__PrepareResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_moz1__Prepare.key = key;
	soap_tmp_moz1__Prepare.query = query;
	soap_tmp_moz1__Prepare.name = name;
	soap_tmp_moz1__Prepare.arity = arity;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_moz1__Prepare(soap, &soap_tmp_moz1__Prepare);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__Prepare(soap, &soap_tmp_moz1__Prepare, "moz1:Prepare", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__Prepare(soap, &soap_tmp_moz1__Prepare, "moz1:Prepare", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_unsignedInt(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_moz1__PrepareResponse = soap_get_moz1__PrepareResponse(soap, NULL, "moz1:PrepareResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_moz1__PrepareResponse->result)
		*result = *soap_tmp_moz1__PrepareResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_moz1__PrepareList(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, struct moz1__sqlQueryList *queries, unsigned int *result)
{	struct moz1__PrepareList soap_tmp_moz1__PrepareList;
	struct moz1__PrepareListResponse *soap_tmp_moz1__PrepareListResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_moz1__PrepareList.key = key;
	soap_tmp_moz1__PrepareList.queries = queries;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_moz1__PrepareList(soap, &soap_tmp_moz1__PrepareList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__PrepareList(soap, &soap_tmp_moz1__PrepareList, "moz1:PrepareList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__PrepareList(soap, &soap_tmp_moz1__PrepareList, "moz1:PrepareList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_unsignedInt(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_moz1__PrepareListResponse = soap_get_moz1__PrepareListResponse(soap, NULL, "moz1:PrepareListResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_moz1__PrepareListResponse->result)
		*result = *soap_tmp_moz1__PrepareListResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_moz1__ExecPreparedSelect(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *name, struct moz1__sqlLine *params, struct moz1__ExecPreparedSelectResponse *_param_2)
{	struct moz1__ExecPreparedSelect soap_tmp_moz1__ExecPreparedSelect;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_moz1__ExecPreparedSelect.key = key;
	soap_tmp_moz1__ExecPreparedSelect.name = name;
	soap_tmp_moz1__ExecPreparedSelect.params = params;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_moz1__ExecPreparedSelect(soap, &soap_tmp_moz1__ExecPreparedSelect);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__ExecPreparedSelect(soap, &soap_tmp_moz1__ExecPreparedSelect, "moz1:ExecPreparedSelect", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__ExecPreparedSelect(soap, &soap_tmp_moz1__ExecPreparedSelect, "moz1:ExecPreparedSelect", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_moz1__ExecPreparedSelectResponse(soap, _param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_moz1__ExecPreparedSelectResponse(soap, _param_2, "moz1:ExecPreparedSelectResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_moz1__ExecPreparedUpdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *name, struct moz1__sqlLine *params, char **result)
{	struct moz1__ExecPreparedUpdate soap_tmp_moz1__ExecPreparedUpdate;
	struct moz1__ExecPreparedUpdateResponse *soap_tmp_moz1__ExecPreparedUpdateResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_moz1__ExecPreparedUpdate.key = key;
	soap_tmp_moz1__ExecPreparedUpdate.name = name;
	soap_tmp_moz1__ExecPreparedUpdate.params = params;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_moz1__ExecPreparedUpdate(soap, &soap_tmp_moz1__ExecPreparedUpdate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__ExecPreparedUpdate(soap, &soap_tmp_moz1__ExecPreparedUpdate, "moz1:ExecPreparedUpdate", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__ExecPreparedUpdate(soap, &soap_tmp_moz1__ExecPreparedUpdate, "moz1:ExecPreparedUpdate", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	*result = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_moz1__ExecPreparedUpdateResponse = soap_get_moz1__ExecPreparedUpdateResponse(soap, NULL, "moz1:ExecPreparedUpdateResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_moz1__ExecPreparedUpdateResponse->result)
		*result = *soap_tmp_moz1__ExecPreparedUpdateResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_moz1__ExecSelect(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *query, struct moz1__sqlLine *params, struct moz1__ExecSelectResponse *_param_3)
{	struct moz1__ExecSelect soap_tmp_moz1__ExecSelect;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_moz1__ExecSelect.key = key;
	soap_tmp_moz1__ExecSelect.query = query;
	soap_tmp_moz1__ExecSelect.params = params;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_moz1__ExecSelect(soap, &soap_tmp_moz1__ExecSelect);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__ExecSelect(soap, &soap_tmp_moz1__ExecSelect, "moz1:ExecSelect", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__ExecSelect(soap, &soap_tmp_moz1__ExecSelect, "moz1:ExecSelect", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_moz1__ExecSelectResponse(soap, _param_3);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_moz1__ExecSelectResponse(soap, _param_3, "moz1:ExecSelectResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_moz1__ExecUpdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *query, struct moz1__sqlLine *params, char **result)
{	struct moz1__ExecUpdate soap_tmp_moz1__ExecUpdate;
	struct moz1__ExecUpdateResponse *soap_tmp_moz1__ExecUpdateResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_moz1__ExecUpdate.key = key;
	soap_tmp_moz1__ExecUpdate.query = query;
	soap_tmp_moz1__ExecUpdate.params = params;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_moz1__ExecUpdate(soap, &soap_tmp_moz1__ExecUpdate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__ExecUpdate(soap, &soap_tmp_moz1__ExecUpdate, "moz1:ExecUpdate", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__ExecUpdate(soap, &soap_tmp_moz1__ExecUpdate, "moz1:ExecUpdate", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	*result = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_moz1__ExecUpdateResponse = soap_get_moz1__ExecUpdateResponse(soap, NULL, "moz1:ExecUpdateResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_moz1__ExecUpdateResponse->result)
		*result = *soap_tmp_moz1__ExecUpdateResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_moz1__pmInit(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *database, enum xsd__boolean force, unsigned int *result)
{	struct moz1__pmInit soap_tmp_moz1__pmInit;
	struct moz1__pmInitResponse *soap_tmp_moz1__pmInitResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_moz1__pmInit.key = key;
	soap_tmp_moz1__pmInit.database = database;
	soap_tmp_moz1__pmInit.force = force;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_moz1__pmInit(soap, &soap_tmp_moz1__pmInit);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__pmInit(soap, &soap_tmp_moz1__pmInit, "moz1:pmInit", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__pmInit(soap, &soap_tmp_moz1__pmInit, "moz1:pmInit", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_unsignedInt(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_moz1__pmInitResponse = soap_get_moz1__pmInitResponse(soap, NULL, "moz1:pmInitResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_moz1__pmInitResponse->result)
		*result = *soap_tmp_moz1__pmInitResponse->result;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of mozClient.c */
