/* mozH.h
   Generated by gSOAP 2.7.6e from comptax.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef mozH_H
#define mozH_H
#include "mozStub.h"
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
#endif

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, enum xsd__boolean *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const enum xsd__boolean *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const enum xsd__boolean *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__boolean2s(struct soap*, enum xsd__boolean);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, enum xsd__boolean *, const char*, const char*);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, enum xsd__boolean *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__boolean(struct soap*, const char*, enum xsd__boolean *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_moz1__pmInit
#define SOAP_TYPE_moz1__pmInit (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__pmInit(struct soap*, const struct moz1__pmInit *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__pmInit(struct soap*, struct moz1__pmInit *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__pmInit(struct soap*, const struct moz1__pmInit *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__pmInit(struct soap*, const char*, int, const struct moz1__pmInit *, const char*);
SOAP_FMAC3 struct moz1__pmInit * SOAP_FMAC4 soap_get_moz1__pmInit(struct soap*, struct moz1__pmInit *, const char*, const char*);
SOAP_FMAC3 struct moz1__pmInit * SOAP_FMAC4 soap_in_moz1__pmInit(struct soap*, const char*, struct moz1__pmInit *, const char*);

#ifndef SOAP_TYPE_moz1__pmInitResponse
#define SOAP_TYPE_moz1__pmInitResponse (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__pmInitResponse(struct soap*, const struct moz1__pmInitResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__pmInitResponse(struct soap*, struct moz1__pmInitResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__pmInitResponse(struct soap*, const struct moz1__pmInitResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__pmInitResponse(struct soap*, const char*, int, const struct moz1__pmInitResponse *, const char*);
SOAP_FMAC3 struct moz1__pmInitResponse * SOAP_FMAC4 soap_get_moz1__pmInitResponse(struct soap*, struct moz1__pmInitResponse *, const char*, const char*);
SOAP_FMAC3 struct moz1__pmInitResponse * SOAP_FMAC4 soap_in_moz1__pmInitResponse(struct soap*, const char*, struct moz1__pmInitResponse *, const char*);

#ifndef SOAP_TYPE_moz1__ExecUpdate
#define SOAP_TYPE_moz1__ExecUpdate (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__ExecUpdate(struct soap*, const struct moz1__ExecUpdate *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__ExecUpdate(struct soap*, struct moz1__ExecUpdate *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__ExecUpdate(struct soap*, const struct moz1__ExecUpdate *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__ExecUpdate(struct soap*, const char*, int, const struct moz1__ExecUpdate *, const char*);
SOAP_FMAC3 struct moz1__ExecUpdate * SOAP_FMAC4 soap_get_moz1__ExecUpdate(struct soap*, struct moz1__ExecUpdate *, const char*, const char*);
SOAP_FMAC3 struct moz1__ExecUpdate * SOAP_FMAC4 soap_in_moz1__ExecUpdate(struct soap*, const char*, struct moz1__ExecUpdate *, const char*);

#ifndef SOAP_TYPE_moz1__ExecUpdateResponse
#define SOAP_TYPE_moz1__ExecUpdateResponse (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__ExecUpdateResponse(struct soap*, const struct moz1__ExecUpdateResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__ExecUpdateResponse(struct soap*, struct moz1__ExecUpdateResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__ExecUpdateResponse(struct soap*, const struct moz1__ExecUpdateResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__ExecUpdateResponse(struct soap*, const char*, int, const struct moz1__ExecUpdateResponse *, const char*);
SOAP_FMAC3 struct moz1__ExecUpdateResponse * SOAP_FMAC4 soap_get_moz1__ExecUpdateResponse(struct soap*, struct moz1__ExecUpdateResponse *, const char*, const char*);
SOAP_FMAC3 struct moz1__ExecUpdateResponse * SOAP_FMAC4 soap_in_moz1__ExecUpdateResponse(struct soap*, const char*, struct moz1__ExecUpdateResponse *, const char*);

#ifndef SOAP_TYPE_moz1__ExecSelect
#define SOAP_TYPE_moz1__ExecSelect (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__ExecSelect(struct soap*, const struct moz1__ExecSelect *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__ExecSelect(struct soap*, struct moz1__ExecSelect *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__ExecSelect(struct soap*, const struct moz1__ExecSelect *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__ExecSelect(struct soap*, const char*, int, const struct moz1__ExecSelect *, const char*);
SOAP_FMAC3 struct moz1__ExecSelect * SOAP_FMAC4 soap_get_moz1__ExecSelect(struct soap*, struct moz1__ExecSelect *, const char*, const char*);
SOAP_FMAC3 struct moz1__ExecSelect * SOAP_FMAC4 soap_in_moz1__ExecSelect(struct soap*, const char*, struct moz1__ExecSelect *, const char*);

#ifndef SOAP_TYPE_moz1__ExecSelectResponse
#define SOAP_TYPE_moz1__ExecSelectResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__ExecSelectResponse(struct soap*, const struct moz1__ExecSelectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__ExecSelectResponse(struct soap*, struct moz1__ExecSelectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__ExecSelectResponse(struct soap*, const struct moz1__ExecSelectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__ExecSelectResponse(struct soap*, const char*, int, const struct moz1__ExecSelectResponse *, const char*);
SOAP_FMAC3 struct moz1__ExecSelectResponse * SOAP_FMAC4 soap_get_moz1__ExecSelectResponse(struct soap*, struct moz1__ExecSelectResponse *, const char*, const char*);
SOAP_FMAC3 struct moz1__ExecSelectResponse * SOAP_FMAC4 soap_in_moz1__ExecSelectResponse(struct soap*, const char*, struct moz1__ExecSelectResponse *, const char*);

#ifndef SOAP_TYPE_moz1__ExecPreparedUpdate
#define SOAP_TYPE_moz1__ExecPreparedUpdate (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__ExecPreparedUpdate(struct soap*, const struct moz1__ExecPreparedUpdate *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__ExecPreparedUpdate(struct soap*, struct moz1__ExecPreparedUpdate *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__ExecPreparedUpdate(struct soap*, const struct moz1__ExecPreparedUpdate *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__ExecPreparedUpdate(struct soap*, const char*, int, const struct moz1__ExecPreparedUpdate *, const char*);
SOAP_FMAC3 struct moz1__ExecPreparedUpdate * SOAP_FMAC4 soap_get_moz1__ExecPreparedUpdate(struct soap*, struct moz1__ExecPreparedUpdate *, const char*, const char*);
SOAP_FMAC3 struct moz1__ExecPreparedUpdate * SOAP_FMAC4 soap_in_moz1__ExecPreparedUpdate(struct soap*, const char*, struct moz1__ExecPreparedUpdate *, const char*);

#ifndef SOAP_TYPE_moz1__ExecPreparedUpdateResponse
#define SOAP_TYPE_moz1__ExecPreparedUpdateResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__ExecPreparedUpdateResponse(struct soap*, const struct moz1__ExecPreparedUpdateResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__ExecPreparedUpdateResponse(struct soap*, struct moz1__ExecPreparedUpdateResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__ExecPreparedUpdateResponse(struct soap*, const struct moz1__ExecPreparedUpdateResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__ExecPreparedUpdateResponse(struct soap*, const char*, int, const struct moz1__ExecPreparedUpdateResponse *, const char*);
SOAP_FMAC3 struct moz1__ExecPreparedUpdateResponse * SOAP_FMAC4 soap_get_moz1__ExecPreparedUpdateResponse(struct soap*, struct moz1__ExecPreparedUpdateResponse *, const char*, const char*);
SOAP_FMAC3 struct moz1__ExecPreparedUpdateResponse * SOAP_FMAC4 soap_in_moz1__ExecPreparedUpdateResponse(struct soap*, const char*, struct moz1__ExecPreparedUpdateResponse *, const char*);

#ifndef SOAP_TYPE_moz1__ExecPreparedSelect
#define SOAP_TYPE_moz1__ExecPreparedSelect (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__ExecPreparedSelect(struct soap*, const struct moz1__ExecPreparedSelect *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__ExecPreparedSelect(struct soap*, struct moz1__ExecPreparedSelect *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__ExecPreparedSelect(struct soap*, const struct moz1__ExecPreparedSelect *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__ExecPreparedSelect(struct soap*, const char*, int, const struct moz1__ExecPreparedSelect *, const char*);
SOAP_FMAC3 struct moz1__ExecPreparedSelect * SOAP_FMAC4 soap_get_moz1__ExecPreparedSelect(struct soap*, struct moz1__ExecPreparedSelect *, const char*, const char*);
SOAP_FMAC3 struct moz1__ExecPreparedSelect * SOAP_FMAC4 soap_in_moz1__ExecPreparedSelect(struct soap*, const char*, struct moz1__ExecPreparedSelect *, const char*);

#ifndef SOAP_TYPE_moz1__ExecPreparedSelectResponse
#define SOAP_TYPE_moz1__ExecPreparedSelectResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__ExecPreparedSelectResponse(struct soap*, const struct moz1__ExecPreparedSelectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__ExecPreparedSelectResponse(struct soap*, struct moz1__ExecPreparedSelectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__ExecPreparedSelectResponse(struct soap*, const struct moz1__ExecPreparedSelectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__ExecPreparedSelectResponse(struct soap*, const char*, int, const struct moz1__ExecPreparedSelectResponse *, const char*);
SOAP_FMAC3 struct moz1__ExecPreparedSelectResponse * SOAP_FMAC4 soap_get_moz1__ExecPreparedSelectResponse(struct soap*, struct moz1__ExecPreparedSelectResponse *, const char*, const char*);
SOAP_FMAC3 struct moz1__ExecPreparedSelectResponse * SOAP_FMAC4 soap_in_moz1__ExecPreparedSelectResponse(struct soap*, const char*, struct moz1__ExecPreparedSelectResponse *, const char*);

#ifndef SOAP_TYPE_moz1__PrepareList
#define SOAP_TYPE_moz1__PrepareList (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__PrepareList(struct soap*, const struct moz1__PrepareList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__PrepareList(struct soap*, struct moz1__PrepareList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__PrepareList(struct soap*, const struct moz1__PrepareList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__PrepareList(struct soap*, const char*, int, const struct moz1__PrepareList *, const char*);
SOAP_FMAC3 struct moz1__PrepareList * SOAP_FMAC4 soap_get_moz1__PrepareList(struct soap*, struct moz1__PrepareList *, const char*, const char*);
SOAP_FMAC3 struct moz1__PrepareList * SOAP_FMAC4 soap_in_moz1__PrepareList(struct soap*, const char*, struct moz1__PrepareList *, const char*);

#ifndef SOAP_TYPE_moz1__PrepareListResponse
#define SOAP_TYPE_moz1__PrepareListResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__PrepareListResponse(struct soap*, const struct moz1__PrepareListResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__PrepareListResponse(struct soap*, struct moz1__PrepareListResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__PrepareListResponse(struct soap*, const struct moz1__PrepareListResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__PrepareListResponse(struct soap*, const char*, int, const struct moz1__PrepareListResponse *, const char*);
SOAP_FMAC3 struct moz1__PrepareListResponse * SOAP_FMAC4 soap_get_moz1__PrepareListResponse(struct soap*, struct moz1__PrepareListResponse *, const char*, const char*);
SOAP_FMAC3 struct moz1__PrepareListResponse * SOAP_FMAC4 soap_in_moz1__PrepareListResponse(struct soap*, const char*, struct moz1__PrepareListResponse *, const char*);

#ifndef SOAP_TYPE_moz1__Prepare
#define SOAP_TYPE_moz1__Prepare (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__Prepare(struct soap*, const struct moz1__Prepare *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__Prepare(struct soap*, struct moz1__Prepare *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__Prepare(struct soap*, const struct moz1__Prepare *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__Prepare(struct soap*, const char*, int, const struct moz1__Prepare *, const char*);
SOAP_FMAC3 struct moz1__Prepare * SOAP_FMAC4 soap_get_moz1__Prepare(struct soap*, struct moz1__Prepare *, const char*, const char*);
SOAP_FMAC3 struct moz1__Prepare * SOAP_FMAC4 soap_in_moz1__Prepare(struct soap*, const char*, struct moz1__Prepare *, const char*);

#ifndef SOAP_TYPE_moz1__PrepareResponse
#define SOAP_TYPE_moz1__PrepareResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__PrepareResponse(struct soap*, const struct moz1__PrepareResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__PrepareResponse(struct soap*, struct moz1__PrepareResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__PrepareResponse(struct soap*, const struct moz1__PrepareResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__PrepareResponse(struct soap*, const char*, int, const struct moz1__PrepareResponse *, const char*);
SOAP_FMAC3 struct moz1__PrepareResponse * SOAP_FMAC4 soap_get_moz1__PrepareResponse(struct soap*, struct moz1__PrepareResponse *, const char*, const char*);
SOAP_FMAC3 struct moz1__PrepareResponse * SOAP_FMAC4 soap_in_moz1__PrepareResponse(struct soap*, const char*, struct moz1__PrepareResponse *, const char*);

#ifndef SOAP_TYPE_moz1__Setup
#define SOAP_TYPE_moz1__Setup (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__Setup(struct soap*, const struct moz1__Setup *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__Setup(struct soap*, struct moz1__Setup *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__Setup(struct soap*, const struct moz1__Setup *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__Setup(struct soap*, const char*, int, const struct moz1__Setup *, const char*);
SOAP_FMAC3 struct moz1__Setup * SOAP_FMAC4 soap_get_moz1__Setup(struct soap*, struct moz1__Setup *, const char*, const char*);
SOAP_FMAC3 struct moz1__Setup * SOAP_FMAC4 soap_in_moz1__Setup(struct soap*, const char*, struct moz1__Setup *, const char*);

#ifndef SOAP_TYPE_moz1__SetupResponse
#define SOAP_TYPE_moz1__SetupResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__SetupResponse(struct soap*, const struct moz1__SetupResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__SetupResponse(struct soap*, struct moz1__SetupResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__SetupResponse(struct soap*, const struct moz1__SetupResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__SetupResponse(struct soap*, const char*, int, const struct moz1__SetupResponse *, const char*);
SOAP_FMAC3 struct moz1__SetupResponse * SOAP_FMAC4 soap_get_moz1__SetupResponse(struct soap*, struct moz1__SetupResponse *, const char*, const char*);
SOAP_FMAC3 struct moz1__SetupResponse * SOAP_FMAC4 soap_in_moz1__SetupResponse(struct soap*, const char*, struct moz1__SetupResponse *, const char*);

#ifndef SOAP_TYPE_moz1__pmFinish
#define SOAP_TYPE_moz1__pmFinish (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__pmFinish(struct soap*, const struct moz1__pmFinish *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__pmFinish(struct soap*, struct moz1__pmFinish *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__pmFinish(struct soap*, const struct moz1__pmFinish *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__pmFinish(struct soap*, const char*, int, const struct moz1__pmFinish *, const char*);
SOAP_FMAC3 struct moz1__pmFinish * SOAP_FMAC4 soap_get_moz1__pmFinish(struct soap*, struct moz1__pmFinish *, const char*, const char*);
SOAP_FMAC3 struct moz1__pmFinish * SOAP_FMAC4 soap_in_moz1__pmFinish(struct soap*, const char*, struct moz1__pmFinish *, const char*);

#ifndef SOAP_TYPE_moz1__pmFinishResponse
#define SOAP_TYPE_moz1__pmFinishResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__pmFinishResponse(struct soap*, const struct moz1__pmFinishResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__pmFinishResponse(struct soap*, struct moz1__pmFinishResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__pmFinishResponse(struct soap*, const struct moz1__pmFinishResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__pmFinishResponse(struct soap*, const char*, int, const struct moz1__pmFinishResponse *, const char*);
SOAP_FMAC3 struct moz1__pmFinishResponse * SOAP_FMAC4 soap_get_moz1__pmFinishResponse(struct soap*, struct moz1__pmFinishResponse *, const char*, const char*);
SOAP_FMAC3 struct moz1__pmFinishResponse * SOAP_FMAC4 soap_in_moz1__pmFinishResponse(struct soap*, const char*, struct moz1__pmFinishResponse *, const char*);

#ifndef SOAP_TYPE_moz1__pmConnect
#define SOAP_TYPE_moz1__pmConnect (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__pmConnect(struct soap*, const struct moz1__pmConnect *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__pmConnect(struct soap*, struct moz1__pmConnect *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__pmConnect(struct soap*, const struct moz1__pmConnect *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__pmConnect(struct soap*, const char*, int, const struct moz1__pmConnect *, const char*);
SOAP_FMAC3 struct moz1__pmConnect * SOAP_FMAC4 soap_get_moz1__pmConnect(struct soap*, struct moz1__pmConnect *, const char*, const char*);
SOAP_FMAC3 struct moz1__pmConnect * SOAP_FMAC4 soap_in_moz1__pmConnect(struct soap*, const char*, struct moz1__pmConnect *, const char*);

#ifndef SOAP_TYPE_moz1__pmConnectResponse
#define SOAP_TYPE_moz1__pmConnectResponse (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__pmConnectResponse(struct soap*, const struct moz1__pmConnectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__pmConnectResponse(struct soap*, struct moz1__pmConnectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__pmConnectResponse(struct soap*, const struct moz1__pmConnectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__pmConnectResponse(struct soap*, const char*, int, const struct moz1__pmConnectResponse *, const char*);
SOAP_FMAC3 struct moz1__pmConnectResponse * SOAP_FMAC4 soap_get_moz1__pmConnectResponse(struct soap*, struct moz1__pmConnectResponse *, const char*, const char*);
SOAP_FMAC3 struct moz1__pmConnectResponse * SOAP_FMAC4 soap_in_moz1__pmConnectResponse(struct soap*, const char*, struct moz1__pmConnectResponse *, const char*);

#ifndef SOAP_TYPE__moz1__sqlQueryList_def
#define SOAP_TYPE__moz1__sqlQueryList_def (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__moz1__sqlQueryList_def(struct soap*, const struct _moz1__sqlQueryList_def *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default__moz1__sqlQueryList_def(struct soap*, struct _moz1__sqlQueryList_def *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__moz1__sqlQueryList_def(struct soap*, const struct _moz1__sqlQueryList_def *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__moz1__sqlQueryList_def(struct soap*, const char*, int, const struct _moz1__sqlQueryList_def *, const char*);
SOAP_FMAC3 struct _moz1__sqlQueryList_def * SOAP_FMAC4 soap_get__moz1__sqlQueryList_def(struct soap*, struct _moz1__sqlQueryList_def *, const char*, const char*);
SOAP_FMAC3 struct _moz1__sqlQueryList_def * SOAP_FMAC4 soap_in__moz1__sqlQueryList_def(struct soap*, const char*, struct _moz1__sqlQueryList_def *, const char*);

#ifndef SOAP_TYPE_moz1__sqlQueryList
#define SOAP_TYPE_moz1__sqlQueryList (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__sqlQueryList(struct soap*, const struct moz1__sqlQueryList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__sqlQueryList(struct soap*, struct moz1__sqlQueryList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__sqlQueryList(struct soap*, const struct moz1__sqlQueryList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__sqlQueryList(struct soap*, const char*, int, const struct moz1__sqlQueryList *, const char*);
SOAP_FMAC3 struct moz1__sqlQueryList * SOAP_FMAC4 soap_get_moz1__sqlQueryList(struct soap*, struct moz1__sqlQueryList *, const char*, const char*);
SOAP_FMAC3 struct moz1__sqlQueryList * SOAP_FMAC4 soap_in_moz1__sqlQueryList(struct soap*, const char*, struct moz1__sqlQueryList *, const char*);

#ifndef SOAP_TYPE_moz1__sqlTable
#define SOAP_TYPE_moz1__sqlTable (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__sqlTable(struct soap*, const struct moz1__sqlTable *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__sqlTable(struct soap*, struct moz1__sqlTable *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__sqlTable(struct soap*, const struct moz1__sqlTable *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__sqlTable(struct soap*, const char*, int, const struct moz1__sqlTable *, const char*);
SOAP_FMAC3 struct moz1__sqlTable * SOAP_FMAC4 soap_get_moz1__sqlTable(struct soap*, struct moz1__sqlTable *, const char*, const char*);
SOAP_FMAC3 struct moz1__sqlTable * SOAP_FMAC4 soap_in_moz1__sqlTable(struct soap*, const char*, struct moz1__sqlTable *, const char*);

#ifndef SOAP_TYPE_moz1__sqlLine
#define SOAP_TYPE_moz1__sqlLine (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_moz1__sqlLine(struct soap*, const struct moz1__sqlLine *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_moz1__sqlLine(struct soap*, struct moz1__sqlLine *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_moz1__sqlLine(struct soap*, const struct moz1__sqlLine *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_moz1__sqlLine(struct soap*, const char*, int, const struct moz1__sqlLine *, const char*);
SOAP_FMAC3 struct moz1__sqlLine * SOAP_FMAC4 soap_get_moz1__sqlLine(struct soap*, struct moz1__sqlLine *, const char*, const char*);
SOAP_FMAC3 struct moz1__sqlLine * SOAP_FMAC4 soap_in_moz1__sqlLine(struct soap*, const char*, struct moz1__sqlLine *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTomoz1__ExecSelectResponse
#define SOAP_TYPE_PointerTomoz1__ExecSelectResponse (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomoz1__ExecSelectResponse(struct soap*, struct moz1__ExecSelectResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomoz1__ExecSelectResponse(struct soap*, struct moz1__ExecSelectResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomoz1__ExecSelectResponse(struct soap*, const char *, int, struct moz1__ExecSelectResponse *const*, const char *);
SOAP_FMAC3 struct moz1__ExecSelectResponse ** SOAP_FMAC4 soap_get_PointerTomoz1__ExecSelectResponse(struct soap*, struct moz1__ExecSelectResponse **, const char*, const char*);
SOAP_FMAC3 struct moz1__ExecSelectResponse ** SOAP_FMAC4 soap_in_PointerTomoz1__ExecSelectResponse(struct soap*, const char*, struct moz1__ExecSelectResponse **, const char*);

#ifndef SOAP_TYPE_PointerTomoz1__ExecPreparedSelectResponse
#define SOAP_TYPE_PointerTomoz1__ExecPreparedSelectResponse (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomoz1__ExecPreparedSelectResponse(struct soap*, struct moz1__ExecPreparedSelectResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomoz1__ExecPreparedSelectResponse(struct soap*, struct moz1__ExecPreparedSelectResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomoz1__ExecPreparedSelectResponse(struct soap*, const char *, int, struct moz1__ExecPreparedSelectResponse *const*, const char *);
SOAP_FMAC3 struct moz1__ExecPreparedSelectResponse ** SOAP_FMAC4 soap_get_PointerTomoz1__ExecPreparedSelectResponse(struct soap*, struct moz1__ExecPreparedSelectResponse **, const char*, const char*);
SOAP_FMAC3 struct moz1__ExecPreparedSelectResponse ** SOAP_FMAC4 soap_in_PointerTomoz1__ExecPreparedSelectResponse(struct soap*, const char*, struct moz1__ExecPreparedSelectResponse **, const char*);

#ifndef SOAP_TYPE_PointerTomoz1__sqlTable
#define SOAP_TYPE_PointerTomoz1__sqlTable (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomoz1__sqlTable(struct soap*, struct moz1__sqlTable *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomoz1__sqlTable(struct soap*, struct moz1__sqlTable *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomoz1__sqlTable(struct soap*, const char *, int, struct moz1__sqlTable *const*, const char *);
SOAP_FMAC3 struct moz1__sqlTable ** SOAP_FMAC4 soap_get_PointerTomoz1__sqlTable(struct soap*, struct moz1__sqlTable **, const char*, const char*);
SOAP_FMAC3 struct moz1__sqlTable ** SOAP_FMAC4 soap_in_PointerTomoz1__sqlTable(struct soap*, const char*, struct moz1__sqlTable **, const char*);

#ifndef SOAP_TYPE_PointerTomoz1__sqlQueryList
#define SOAP_TYPE_PointerTomoz1__sqlQueryList (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomoz1__sqlQueryList(struct soap*, struct moz1__sqlQueryList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomoz1__sqlQueryList(struct soap*, struct moz1__sqlQueryList *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomoz1__sqlQueryList(struct soap*, const char *, int, struct moz1__sqlQueryList *const*, const char *);
SOAP_FMAC3 struct moz1__sqlQueryList ** SOAP_FMAC4 soap_get_PointerTomoz1__sqlQueryList(struct soap*, struct moz1__sqlQueryList **, const char*, const char*);
SOAP_FMAC3 struct moz1__sqlQueryList ** SOAP_FMAC4 soap_in_PointerTomoz1__sqlQueryList(struct soap*, const char*, struct moz1__sqlQueryList **, const char*);

#ifndef SOAP_TYPE_PointerTomoz1__SetupResponse
#define SOAP_TYPE_PointerTomoz1__SetupResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomoz1__SetupResponse(struct soap*, struct moz1__SetupResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomoz1__SetupResponse(struct soap*, struct moz1__SetupResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomoz1__SetupResponse(struct soap*, const char *, int, struct moz1__SetupResponse *const*, const char *);
SOAP_FMAC3 struct moz1__SetupResponse ** SOAP_FMAC4 soap_get_PointerTomoz1__SetupResponse(struct soap*, struct moz1__SetupResponse **, const char*, const char*);
SOAP_FMAC3 struct moz1__SetupResponse ** SOAP_FMAC4 soap_in_PointerTomoz1__SetupResponse(struct soap*, const char*, struct moz1__SetupResponse **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedInt
#define SOAP_TYPE_PointerTounsignedInt (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedInt(struct soap*, unsigned int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedInt(struct soap*, unsigned int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedInt(struct soap*, const char *, int, unsigned int *const*, const char *);
SOAP_FMAC3 unsigned int ** SOAP_FMAC4 soap_get_PointerTounsignedInt(struct soap*, unsigned int **, const char*, const char*);
SOAP_FMAC3 unsigned int ** SOAP_FMAC4 soap_in_PointerTounsignedInt(struct soap*, const char*, unsigned int **, const char*);

#ifndef SOAP_TYPE_PointerTo_moz1__sqlQueryList_def
#define SOAP_TYPE_PointerTo_moz1__sqlQueryList_def (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_moz1__sqlQueryList_def(struct soap*, struct _moz1__sqlQueryList_def *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_moz1__sqlQueryList_def(struct soap*, struct _moz1__sqlQueryList_def *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_moz1__sqlQueryList_def(struct soap*, const char *, int, struct _moz1__sqlQueryList_def *const*, const char *);
SOAP_FMAC3 struct _moz1__sqlQueryList_def ** SOAP_FMAC4 soap_get_PointerTo_moz1__sqlQueryList_def(struct soap*, struct _moz1__sqlQueryList_def **, const char*, const char*);
SOAP_FMAC3 struct _moz1__sqlQueryList_def ** SOAP_FMAC4 soap_in_PointerTo_moz1__sqlQueryList_def(struct soap*, const char*, struct _moz1__sqlQueryList_def **, const char*);

#ifndef SOAP_TYPE_PointerTomoz1__sqlLine
#define SOAP_TYPE_PointerTomoz1__sqlLine (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomoz1__sqlLine(struct soap*, struct moz1__sqlLine *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomoz1__sqlLine(struct soap*, struct moz1__sqlLine *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomoz1__sqlLine(struct soap*, const char *, int, struct moz1__sqlLine *const*, const char *);
SOAP_FMAC3 struct moz1__sqlLine ** SOAP_FMAC4 soap_get_PointerTomoz1__sqlLine(struct soap*, struct moz1__sqlLine **, const char*, const char*);
SOAP_FMAC3 struct moz1__sqlLine ** SOAP_FMAC4 soap_in_PointerTomoz1__sqlLine(struct soap*, const char*, struct moz1__sqlLine **, const char*);

#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of mozH.h */
