/* mozServer.c
   Generated by gSOAP 2.7.6e from comptax.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "mozH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) mozServer.c ver 2.7.6e 2007-02-01 08:00:53 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (!--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "moz1:pmConnect"))
		return soap_serve_moz1__pmConnect(soap);
	if (!soap_match_tag(soap, soap->tag, "moz1:pmFinish"))
		return soap_serve_moz1__pmFinish(soap);
	if (!soap_match_tag(soap, soap->tag, "moz1:Setup"))
		return soap_serve_moz1__Setup(soap);
	if (!soap_match_tag(soap, soap->tag, "moz1:Prepare"))
		return soap_serve_moz1__Prepare(soap);
	if (!soap_match_tag(soap, soap->tag, "moz1:PrepareList"))
		return soap_serve_moz1__PrepareList(soap);
	if (!soap_match_tag(soap, soap->tag, "moz1:ExecPreparedSelect"))
		return soap_serve_moz1__ExecPreparedSelect(soap);
	if (!soap_match_tag(soap, soap->tag, "moz1:ExecPreparedUpdate"))
		return soap_serve_moz1__ExecPreparedUpdate(soap);
	if (!soap_match_tag(soap, soap->tag, "moz1:ExecSelect"))
		return soap_serve_moz1__ExecSelect(soap);
	if (!soap_match_tag(soap, soap->tag, "moz1:ExecUpdate"))
		return soap_serve_moz1__ExecUpdate(soap);
	if (!soap_match_tag(soap, soap->tag, "moz1:pmInit"))
		return soap_serve_moz1__pmInit(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_moz1__pmConnect(struct soap *soap)
{	struct moz1__pmConnect soap_tmp_moz1__pmConnect;
	struct moz1__pmConnectResponse soap_tmp_moz1__pmConnectResponse;
	char * soap_tmp_string;
	soap_default_moz1__pmConnectResponse(soap, &soap_tmp_moz1__pmConnectResponse);
	soap_tmp_string = NULL;
	soap_tmp_moz1__pmConnectResponse.key = &soap_tmp_string;
	soap_default_moz1__pmConnect(soap, &soap_tmp_moz1__pmConnect);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_moz1__pmConnect(soap, &soap_tmp_moz1__pmConnect, "moz1:pmConnect", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = moz1__pmConnect(soap, soap_tmp_moz1__pmConnect.login, soap_tmp_moz1__pmConnect.password, soap_tmp_moz1__pmConnect.database, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_moz1__pmConnectResponse(soap, &soap_tmp_moz1__pmConnectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__pmConnectResponse(soap, &soap_tmp_moz1__pmConnectResponse, "moz1:pmConnectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__pmConnectResponse(soap, &soap_tmp_moz1__pmConnectResponse, "moz1:pmConnectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_moz1__pmFinish(struct soap *soap)
{	struct moz1__pmFinish soap_tmp_moz1__pmFinish;
	struct moz1__pmFinishResponse soap_tmp_moz1__pmFinishResponse;
	unsigned int soap_tmp_unsignedInt;
	soap_default_moz1__pmFinishResponse(soap, &soap_tmp_moz1__pmFinishResponse);
	soap_default_unsignedInt(soap, &soap_tmp_unsignedInt);
	soap_tmp_moz1__pmFinishResponse.result = &soap_tmp_unsignedInt;
	soap_default_moz1__pmFinish(soap, &soap_tmp_moz1__pmFinish);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_moz1__pmFinish(soap, &soap_tmp_moz1__pmFinish, "moz1:pmFinish", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = moz1__pmFinish(soap, soap_tmp_moz1__pmFinish.key, &soap_tmp_unsignedInt);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_moz1__pmFinishResponse(soap, &soap_tmp_moz1__pmFinishResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__pmFinishResponse(soap, &soap_tmp_moz1__pmFinishResponse, "moz1:pmFinishResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__pmFinishResponse(soap, &soap_tmp_moz1__pmFinishResponse, "moz1:pmFinishResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_moz1__Setup(struct soap *soap)
{	struct moz1__Setup soap_tmp_moz1__Setup;
	struct moz1__SetupResponse _param_1;
	soap_default_moz1__SetupResponse(soap, &_param_1);
	soap_default_moz1__Setup(soap, &soap_tmp_moz1__Setup);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_moz1__Setup(soap, &soap_tmp_moz1__Setup, "moz1:Setup", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = moz1__Setup(soap, soap_tmp_moz1__Setup.key, &_param_1);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_moz1__SetupResponse(soap, &_param_1);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__SetupResponse(soap, &_param_1, "moz1:SetupResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__SetupResponse(soap, &_param_1, "moz1:SetupResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_moz1__Prepare(struct soap *soap)
{	struct moz1__Prepare soap_tmp_moz1__Prepare;
	struct moz1__PrepareResponse soap_tmp_moz1__PrepareResponse;
	unsigned int soap_tmp_unsignedInt;
	soap_default_moz1__PrepareResponse(soap, &soap_tmp_moz1__PrepareResponse);
	soap_default_unsignedInt(soap, &soap_tmp_unsignedInt);
	soap_tmp_moz1__PrepareResponse.result = &soap_tmp_unsignedInt;
	soap_default_moz1__Prepare(soap, &soap_tmp_moz1__Prepare);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_moz1__Prepare(soap, &soap_tmp_moz1__Prepare, "moz1:Prepare", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = moz1__Prepare(soap, soap_tmp_moz1__Prepare.key, soap_tmp_moz1__Prepare.query, soap_tmp_moz1__Prepare.name, soap_tmp_moz1__Prepare.arity, &soap_tmp_unsignedInt);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_moz1__PrepareResponse(soap, &soap_tmp_moz1__PrepareResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__PrepareResponse(soap, &soap_tmp_moz1__PrepareResponse, "moz1:PrepareResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__PrepareResponse(soap, &soap_tmp_moz1__PrepareResponse, "moz1:PrepareResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_moz1__PrepareList(struct soap *soap)
{	struct moz1__PrepareList soap_tmp_moz1__PrepareList;
	struct moz1__PrepareListResponse soap_tmp_moz1__PrepareListResponse;
	unsigned int soap_tmp_unsignedInt;
	soap_default_moz1__PrepareListResponse(soap, &soap_tmp_moz1__PrepareListResponse);
	soap_default_unsignedInt(soap, &soap_tmp_unsignedInt);
	soap_tmp_moz1__PrepareListResponse.result = &soap_tmp_unsignedInt;
	soap_default_moz1__PrepareList(soap, &soap_tmp_moz1__PrepareList);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_moz1__PrepareList(soap, &soap_tmp_moz1__PrepareList, "moz1:PrepareList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = moz1__PrepareList(soap, soap_tmp_moz1__PrepareList.key, soap_tmp_moz1__PrepareList.queries, &soap_tmp_unsignedInt);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_moz1__PrepareListResponse(soap, &soap_tmp_moz1__PrepareListResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__PrepareListResponse(soap, &soap_tmp_moz1__PrepareListResponse, "moz1:PrepareListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__PrepareListResponse(soap, &soap_tmp_moz1__PrepareListResponse, "moz1:PrepareListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_moz1__ExecPreparedSelect(struct soap *soap)
{	struct moz1__ExecPreparedSelect soap_tmp_moz1__ExecPreparedSelect;
	struct moz1__ExecPreparedSelectResponse _param_2;
	soap_default_moz1__ExecPreparedSelectResponse(soap, &_param_2);
	soap_default_moz1__ExecPreparedSelect(soap, &soap_tmp_moz1__ExecPreparedSelect);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_moz1__ExecPreparedSelect(soap, &soap_tmp_moz1__ExecPreparedSelect, "moz1:ExecPreparedSelect", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = moz1__ExecPreparedSelect(soap, soap_tmp_moz1__ExecPreparedSelect.key, soap_tmp_moz1__ExecPreparedSelect.name, soap_tmp_moz1__ExecPreparedSelect.params, &_param_2);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_moz1__ExecPreparedSelectResponse(soap, &_param_2);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__ExecPreparedSelectResponse(soap, &_param_2, "moz1:ExecPreparedSelectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__ExecPreparedSelectResponse(soap, &_param_2, "moz1:ExecPreparedSelectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_moz1__ExecPreparedUpdate(struct soap *soap)
{	struct moz1__ExecPreparedUpdate soap_tmp_moz1__ExecPreparedUpdate;
	struct moz1__ExecPreparedUpdateResponse soap_tmp_moz1__ExecPreparedUpdateResponse;
	char * soap_tmp_string;
	soap_default_moz1__ExecPreparedUpdateResponse(soap, &soap_tmp_moz1__ExecPreparedUpdateResponse);
	soap_tmp_string = NULL;
	soap_tmp_moz1__ExecPreparedUpdateResponse.result = &soap_tmp_string;
	soap_default_moz1__ExecPreparedUpdate(soap, &soap_tmp_moz1__ExecPreparedUpdate);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_moz1__ExecPreparedUpdate(soap, &soap_tmp_moz1__ExecPreparedUpdate, "moz1:ExecPreparedUpdate", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = moz1__ExecPreparedUpdate(soap, soap_tmp_moz1__ExecPreparedUpdate.key, soap_tmp_moz1__ExecPreparedUpdate.name, soap_tmp_moz1__ExecPreparedUpdate.params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_moz1__ExecPreparedUpdateResponse(soap, &soap_tmp_moz1__ExecPreparedUpdateResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__ExecPreparedUpdateResponse(soap, &soap_tmp_moz1__ExecPreparedUpdateResponse, "moz1:ExecPreparedUpdateResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__ExecPreparedUpdateResponse(soap, &soap_tmp_moz1__ExecPreparedUpdateResponse, "moz1:ExecPreparedUpdateResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_moz1__ExecSelect(struct soap *soap)
{	struct moz1__ExecSelect soap_tmp_moz1__ExecSelect;
	struct moz1__ExecSelectResponse _param_3;
	soap_default_moz1__ExecSelectResponse(soap, &_param_3);
	soap_default_moz1__ExecSelect(soap, &soap_tmp_moz1__ExecSelect);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_moz1__ExecSelect(soap, &soap_tmp_moz1__ExecSelect, "moz1:ExecSelect", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = moz1__ExecSelect(soap, soap_tmp_moz1__ExecSelect.key, soap_tmp_moz1__ExecSelect.query, soap_tmp_moz1__ExecSelect.params, &_param_3);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_moz1__ExecSelectResponse(soap, &_param_3);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__ExecSelectResponse(soap, &_param_3, "moz1:ExecSelectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__ExecSelectResponse(soap, &_param_3, "moz1:ExecSelectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_moz1__ExecUpdate(struct soap *soap)
{	struct moz1__ExecUpdate soap_tmp_moz1__ExecUpdate;
	struct moz1__ExecUpdateResponse soap_tmp_moz1__ExecUpdateResponse;
	char * soap_tmp_string;
	soap_default_moz1__ExecUpdateResponse(soap, &soap_tmp_moz1__ExecUpdateResponse);
	soap_tmp_string = NULL;
	soap_tmp_moz1__ExecUpdateResponse.result = &soap_tmp_string;
	soap_default_moz1__ExecUpdate(soap, &soap_tmp_moz1__ExecUpdate);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_moz1__ExecUpdate(soap, &soap_tmp_moz1__ExecUpdate, "moz1:ExecUpdate", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = moz1__ExecUpdate(soap, soap_tmp_moz1__ExecUpdate.key, soap_tmp_moz1__ExecUpdate.query, soap_tmp_moz1__ExecUpdate.params, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_moz1__ExecUpdateResponse(soap, &soap_tmp_moz1__ExecUpdateResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__ExecUpdateResponse(soap, &soap_tmp_moz1__ExecUpdateResponse, "moz1:ExecUpdateResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__ExecUpdateResponse(soap, &soap_tmp_moz1__ExecUpdateResponse, "moz1:ExecUpdateResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_moz1__pmInit(struct soap *soap)
{	struct moz1__pmInit soap_tmp_moz1__pmInit;
	struct moz1__pmInitResponse soap_tmp_moz1__pmInitResponse;
	unsigned int soap_tmp_unsignedInt;
	soap_default_moz1__pmInitResponse(soap, &soap_tmp_moz1__pmInitResponse);
	soap_default_unsignedInt(soap, &soap_tmp_unsignedInt);
	soap_tmp_moz1__pmInitResponse.result = &soap_tmp_unsignedInt;
	soap_default_moz1__pmInit(soap, &soap_tmp_moz1__pmInit);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_moz1__pmInit(soap, &soap_tmp_moz1__pmInit, "moz1:pmInit", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = moz1__pmInit(soap, soap_tmp_moz1__pmInit.key, soap_tmp_moz1__pmInit.database, soap_tmp_moz1__pmInit.force, &soap_tmp_unsignedInt);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_moz1__pmInitResponse(soap, &soap_tmp_moz1__pmInitResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_moz1__pmInitResponse(soap, &soap_tmp_moz1__pmInitResponse, "moz1:pmInitResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_moz1__pmInitResponse(soap, &soap_tmp_moz1__pmInitResponse, "moz1:pmInitResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of mozServer.c */
