/* pmC.c
   Generated by gSOAP 2.7.6e from pygmalion.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#include "pmH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) pmC.c ver 2.7.6e 2006-08-22 07:43:14 GMT")


#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serializeheader(struct soap *soap)
{
	if (soap->header)
		soap_serialize_SOAP_ENV__Header(soap, soap->header);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_putheader(struct soap *soap)
{
	if (soap->header)
	{	soap->part = SOAP_IN_HEADER;
		soap_out_SOAP_ENV__Header(soap, "SOAP-ENV:Header", 0, soap->header, NULL);
		soap->part = SOAP_END_HEADER;
	}
	return SOAP_OK;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_getheader(struct soap *soap)
{
	soap->part = SOAP_IN_HEADER;
	soap->header = soap_in_SOAP_ENV__Header(soap, "SOAP-ENV:Header", NULL, NULL);
	soap->part = SOAP_END_HEADER;
	return soap->header == NULL;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_fault(struct soap *soap)
{
	if (!soap->fault)
	{	soap->fault = (struct SOAP_ENV__Fault*)soap_malloc(soap, sizeof(struct SOAP_ENV__Fault));
		soap_default_SOAP_ENV__Fault(soap, soap->fault);
	}
	if (soap->version == 2 && !soap->fault->SOAP_ENV__Code)
	{	soap->fault->SOAP_ENV__Code = (struct SOAP_ENV__Code*)soap_malloc(soap, sizeof(struct SOAP_ENV__Code));
		soap_default_SOAP_ENV__Code(soap, soap->fault->SOAP_ENV__Code);
	}
	if (soap->version == 2 && !soap->fault->SOAP_ENV__Reason)
	{	soap->fault->SOAP_ENV__Reason = (struct SOAP_ENV__Reason*)soap_malloc(soap, sizeof(struct SOAP_ENV__Reason));
		soap_default_SOAP_ENV__Reason(soap, soap->fault->SOAP_ENV__Reason);
	}
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serializefault(struct soap *soap)
{
	if (soap->fault)
		soap_serialize_SOAP_ENV__Fault(soap, soap->fault);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_putfault(struct soap *soap)
{
	if (soap->fault)
		return soap_put_SOAP_ENV__Fault(soap, soap->fault, "SOAP-ENV:Fault", NULL);
	return SOAP_OK;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_getfault(struct soap *soap)
{
	return (soap->fault = soap_get_SOAP_ENV__Fault(soap, NULL, "SOAP-ENV:Fault", NULL)) == NULL;
}

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap)
{
	soap_fault(soap);
	if (soap->version == 2)
		return (const char**)&soap->fault->SOAP_ENV__Code->SOAP_ENV__Value;
	return (const char**)&soap->fault->faultcode;
}

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultsubcode(struct soap *soap)
{
	soap_fault(soap);
	if (soap->version == 2)
	{	if (!soap->fault->SOAP_ENV__Code->SOAP_ENV__Subcode)
		{	soap->fault->SOAP_ENV__Code->SOAP_ENV__Subcode = (struct SOAP_ENV__Code*)soap_malloc(soap, sizeof(struct SOAP_ENV__Code));
			soap_default_SOAP_ENV__Code(soap, soap->fault->SOAP_ENV__Code->SOAP_ENV__Subcode);
		}
		return (const char**)&soap->fault->SOAP_ENV__Code->SOAP_ENV__Subcode->SOAP_ENV__Value;
	}
	return (const char**)&soap->fault->faultcode;
}

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultstring(struct soap *soap)
{
	soap_fault(soap);
	if (soap->version == 2)
		return (const char**)&soap->fault->SOAP_ENV__Reason->SOAP_ENV__Text;
	return (const char**)&soap->fault->faultstring;
}

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultdetail(struct soap *soap)
{
	soap_fault(soap);
	if (soap->version == 1)
	{	if (!soap->fault->detail)
		{	soap->fault->detail = (struct SOAP_ENV__Detail*)soap_malloc(soap, sizeof(struct SOAP_ENV__Detail));
			soap_default_SOAP_ENV__Detail(soap, soap->fault->detail);
		}
		return (const char**)&soap->fault->detail->__any;
	}
	if (!soap->fault->SOAP_ENV__Detail)
	{	soap->fault->SOAP_ENV__Detail = (struct SOAP_ENV__Detail*)soap_malloc(soap, sizeof(struct SOAP_ENV__Detail));
		soap_default_SOAP_ENV__Detail(soap, soap->fault->SOAP_ENV__Detail);
	}
	return (const char**)&soap->fault->SOAP_ENV__Detail->__any;
}

#endif

#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap *soap)
{
	int t;
	for (;;)
		if (!soap_getelement(soap, &t))
			if (soap->error || soap_ignore_element(soap))
				break;
	if (soap->error == SOAP_NO_TAG || soap->error == SOAP_EOF)
		soap->error = SOAP_OK;
	return soap->error;
}
#endif

#ifndef WITH_NOIDREF
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap *soap, int *type)
{
	if (soap_peek_element(soap))
		return NULL;
	if (!*soap->id || !(*type = soap_lookup_type(soap, soap->id)))
		*type = soap_lookup_type(soap, soap->href);
	switch (*type)
	{
	case SOAP_TYPE_byte:
		return soap_in_byte(soap, NULL, NULL, "xsd:byte");
	case SOAP_TYPE_pmns1__Identifiant:
		return soap_in_pmns1__Identifiant(soap, NULL, NULL, "pmns1:Identifiant");
	case SOAP_TYPE_int:
		return soap_in_int(soap, NULL, NULL, "xsd:int");
	case SOAP_TYPE_double:
		return soap_in_double(soap, NULL, NULL, "xsd:double");
	case SOAP_TYPE_pmns1__pmCalcul:
		return soap_in_pmns1__pmCalcul(soap, NULL, NULL, "pmns1:pmCalcul");
	case SOAP_TYPE_pmns1__pmCalculResponse:
		return soap_in_pmns1__pmCalculResponse(soap, NULL, NULL, "pmns1:pmCalculResponse");
	case SOAP_TYPE_pmns1__pmUpdate:
		return soap_in_pmns1__pmUpdate(soap, NULL, NULL, "pmns1:pmUpdate");
	case SOAP_TYPE_pmns1__pmUpdateResponse:
		return soap_in_pmns1__pmUpdateResponse(soap, NULL, NULL, "pmns1:pmUpdateResponse");
	case SOAP_TYPE_pmns1__pmSelect:
		return soap_in_pmns1__pmSelect(soap, NULL, NULL, "pmns1:pmSelect");
	case SOAP_TYPE_pmns1__pmSelectResponse:
		return soap_in_pmns1__pmSelectResponse(soap, NULL, NULL, "pmns1:pmSelectResponse");
	case SOAP_TYPE_pmns1__pmDeconnexion:
		return soap_in_pmns1__pmDeconnexion(soap, NULL, NULL, "pmns1:pmDeconnexion");
	case SOAP_TYPE_pmns1__pmDeconnexionResponse:
		return soap_in_pmns1__pmDeconnexionResponse(soap, NULL, NULL, "pmns1:pmDeconnexionResponse");
	case SOAP_TYPE_pmns1__pmConnexion:
		return soap_in_pmns1__pmConnexion(soap, NULL, NULL, "pmns1:pmConnexion");
	case SOAP_TYPE_pmns1__pmConnexionResponse:
		return soap_in_pmns1__pmConnexionResponse(soap, NULL, NULL, "pmns1:pmConnexionResponse");
	case SOAP_TYPE_pmns1__Resultat:
		return soap_in_pmns1__Resultat(soap, NULL, NULL, "pmns1:Resultat");
	case SOAP_TYPE_pmns1__Ligne:
		return soap_in_pmns1__Ligne(soap, NULL, NULL, "pmns1:Ligne");
	case SOAP_TYPE_PointerTodouble:
		return soap_in_PointerTodouble(soap, NULL, NULL, "xsd:double");
	case SOAP_TYPE_PointerTopmns1__pmSelectResponse:
		return soap_in_PointerTopmns1__pmSelectResponse(soap, NULL, NULL, "pmns1:pmSelectResponse");
	case SOAP_TYPE_PointerTopmns1__Resultat:
		return soap_in_PointerTopmns1__Resultat(soap, NULL, NULL, "pmns1:Resultat");
	case SOAP_TYPE_PointerToint:
		return soap_in_PointerToint(soap, NULL, NULL, "xsd:int");
	case SOAP_TYPE_PointerTopmns1__pmConnexionResponse:
		return soap_in_PointerTopmns1__pmConnexionResponse(soap, NULL, NULL, "pmns1:pmConnexionResponse");
	case SOAP_TYPE_PointerTopmns1__Ligne:
		return soap_in_PointerTopmns1__Ligne(soap, NULL, NULL, "pmns1:Ligne");
	case SOAP_TYPE_PointerTostring:
		return soap_in_PointerTostring(soap, NULL, NULL, "xsd:string");
	case SOAP_TYPE__QName:
	{	char **s;
		s = soap_in__QName(soap, NULL, NULL, "QName");
		return s ? *s : NULL;
	}
	case SOAP_TYPE_string:
	{	char **s;
		s = soap_in_string(soap, NULL, NULL, "xsd:string");
		return s ? *s : NULL;
	}
	default:
	{	const char *t = soap->type;
		if (!*t)
			t = soap->tag;
		if (!soap_match_tag(soap, t, "xsd:byte"))
		{	*type = SOAP_TYPE_byte;
			return soap_in_byte(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "pmns1:Identifiant"))
		{	*type = SOAP_TYPE_pmns1__Identifiant;
			return soap_in_pmns1__Identifiant(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "xsd:int"))
		{	*type = SOAP_TYPE_int;
			return soap_in_int(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "xsd:double"))
		{	*type = SOAP_TYPE_double;
			return soap_in_double(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "pmns1:pmCalcul"))
		{	*type = SOAP_TYPE_pmns1__pmCalcul;
			return soap_in_pmns1__pmCalcul(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "pmns1:pmCalculResponse"))
		{	*type = SOAP_TYPE_pmns1__pmCalculResponse;
			return soap_in_pmns1__pmCalculResponse(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "pmns1:pmUpdate"))
		{	*type = SOAP_TYPE_pmns1__pmUpdate;
			return soap_in_pmns1__pmUpdate(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "pmns1:pmUpdateResponse"))
		{	*type = SOAP_TYPE_pmns1__pmUpdateResponse;
			return soap_in_pmns1__pmUpdateResponse(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "pmns1:pmSelect"))
		{	*type = SOAP_TYPE_pmns1__pmSelect;
			return soap_in_pmns1__pmSelect(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "pmns1:pmSelectResponse"))
		{	*type = SOAP_TYPE_pmns1__pmSelectResponse;
			return soap_in_pmns1__pmSelectResponse(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "pmns1:pmDeconnexion"))
		{	*type = SOAP_TYPE_pmns1__pmDeconnexion;
			return soap_in_pmns1__pmDeconnexion(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "pmns1:pmDeconnexionResponse"))
		{	*type = SOAP_TYPE_pmns1__pmDeconnexionResponse;
			return soap_in_pmns1__pmDeconnexionResponse(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "pmns1:pmConnexion"))
		{	*type = SOAP_TYPE_pmns1__pmConnexion;
			return soap_in_pmns1__pmConnexion(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "pmns1:pmConnexionResponse"))
		{	*type = SOAP_TYPE_pmns1__pmConnexionResponse;
			return soap_in_pmns1__pmConnexionResponse(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "pmns1:Resultat"))
		{	*type = SOAP_TYPE_pmns1__Resultat;
			return soap_in_pmns1__Resultat(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "pmns1:Ligne"))
		{	*type = SOAP_TYPE_pmns1__Ligne;
			return soap_in_pmns1__Ligne(soap, NULL, NULL, NULL);
		}
		if (!soap_match_tag(soap, t, "QName"))
		{	char **s;
			*type = SOAP_TYPE__QName;
			s = soap_in__QName(soap, NULL, NULL, NULL);
			return s ? *s : NULL;
		}
		if (!soap_match_tag(soap, t, "xsd:string"))
		{	char **s;
			*type = SOAP_TYPE_string;
			s = soap_in_string(soap, NULL, NULL, NULL);
			return s ? *s : NULL;
		}
	}
	}
	soap->error = SOAP_TAG_MISMATCH;
	return NULL;
}
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap *soap)
{
	if (!soap_peek_element(soap))
	{	int t;
		if (soap->mustUnderstand && !soap->other)
			return soap->error = SOAP_MUSTUNDERSTAND;
		if (((soap->mode & SOAP_XML_STRICT) && soap->part != SOAP_IN_HEADER) || !soap_match_tag(soap, soap->tag, "SOAP-ENV:"))
			return soap->error = SOAP_TAG_MISMATCH;
		if (!*soap->id || !soap_getelement(soap, &t))
		{	soap->peeked = 0;
			DBGLOG(TEST, SOAP_MESSAGE(fdebug, "Unknown element '%s' (level=%u, %d)\n", soap->tag, soap->level, soap->body));
			if (soap->fignore)
				soap->error = soap->fignore(soap, soap->tag);
			else
				soap->error = SOAP_OK;
			DBGLOG(TEST, if (!soap->error) SOAP_MESSAGE(fdebug, "IGNORING element '%s'\n", soap->tag));
			if (!soap->error && soap->body)
			{	soap->level++;
				while (!soap_ignore_element(soap))
					;
				if (soap->error == SOAP_NO_TAG)
					soap->error = soap_element_end_in(soap, NULL);
			}
		}
	}
	return soap->error;
}

#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap *soap)
{
	int i;
	struct soap_plist *pp;
	if (soap->version == 1 && soap->encodingStyle && !(soap->mode & (SOAP_XML_TREE | SOAP_XML_GRAPH)))
		for (i = 0; i < SOAP_PTRHASH; i++)
			for (pp = soap->pht[i]; pp; pp = pp->next)
				if (pp->mark1 == 2 || pp->mark2 == 2)
					if (soap_putelement(soap, pp->ptr, "id", pp->id, pp->type))
						return soap->error;
	return SOAP_OK;
}
#endif

#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap *soap, const void *ptr, const char *tag, int id, int type)
{
	switch (type)
	{
	case SOAP_TYPE_byte:
		return soap_out_byte(soap, tag, id, (const char *)ptr, "xsd:byte");
	case SOAP_TYPE_pmns1__Identifiant:
		return soap_out_pmns1__Identifiant(soap, tag, id, (const int *)ptr, "pmns1:Identifiant");
	case SOAP_TYPE_int:
		return soap_out_int(soap, tag, id, (const int *)ptr, "xsd:int");
	case SOAP_TYPE_double:
		return soap_out_double(soap, tag, id, (const double *)ptr, "xsd:double");
	case SOAP_TYPE_pmns1__pmCalcul:
		return soap_out_pmns1__pmCalcul(soap, tag, id, (const struct pmns1__pmCalcul *)ptr, "pmns1:pmCalcul");
	case SOAP_TYPE_pmns1__pmCalculResponse:
		return soap_out_pmns1__pmCalculResponse(soap, tag, id, (const struct pmns1__pmCalculResponse *)ptr, "pmns1:pmCalculResponse");
	case SOAP_TYPE_pmns1__pmUpdate:
		return soap_out_pmns1__pmUpdate(soap, tag, id, (const struct pmns1__pmUpdate *)ptr, "pmns1:pmUpdate");
	case SOAP_TYPE_pmns1__pmUpdateResponse:
		return soap_out_pmns1__pmUpdateResponse(soap, tag, id, (const struct pmns1__pmUpdateResponse *)ptr, "pmns1:pmUpdateResponse");
	case SOAP_TYPE_pmns1__pmSelect:
		return soap_out_pmns1__pmSelect(soap, tag, id, (const struct pmns1__pmSelect *)ptr, "pmns1:pmSelect");
	case SOAP_TYPE_pmns1__pmSelectResponse:
		return soap_out_pmns1__pmSelectResponse(soap, tag, id, (const struct pmns1__pmSelectResponse *)ptr, "pmns1:pmSelectResponse");
	case SOAP_TYPE_pmns1__pmDeconnexion:
		return soap_out_pmns1__pmDeconnexion(soap, tag, id, (const struct pmns1__pmDeconnexion *)ptr, "pmns1:pmDeconnexion");
	case SOAP_TYPE_pmns1__pmDeconnexionResponse:
		return soap_out_pmns1__pmDeconnexionResponse(soap, tag, id, (const struct pmns1__pmDeconnexionResponse *)ptr, "pmns1:pmDeconnexionResponse");
	case SOAP_TYPE_pmns1__pmConnexion:
		return soap_out_pmns1__pmConnexion(soap, tag, id, (const struct pmns1__pmConnexion *)ptr, "pmns1:pmConnexion");
	case SOAP_TYPE_pmns1__pmConnexionResponse:
		return soap_out_pmns1__pmConnexionResponse(soap, tag, id, (const struct pmns1__pmConnexionResponse *)ptr, "pmns1:pmConnexionResponse");
	case SOAP_TYPE_pmns1__Resultat:
		return soap_out_pmns1__Resultat(soap, tag, id, (const struct pmns1__Resultat *)ptr, "pmns1:Resultat");
	case SOAP_TYPE_pmns1__Ligne:
		return soap_out_pmns1__Ligne(soap, tag, id, (const struct pmns1__Ligne *)ptr, "pmns1:Ligne");
	case SOAP_TYPE_PointerTodouble:
		return soap_out_PointerTodouble(soap, tag, id, (double *const*)ptr, "xsd:double");
	case SOAP_TYPE_PointerTopmns1__pmSelectResponse:
		return soap_out_PointerTopmns1__pmSelectResponse(soap, tag, id, (struct pmns1__pmSelectResponse *const*)ptr, "pmns1:pmSelectResponse");
	case SOAP_TYPE_PointerTopmns1__Resultat:
		return soap_out_PointerTopmns1__Resultat(soap, tag, id, (struct pmns1__Resultat *const*)ptr, "pmns1:Resultat");
	case SOAP_TYPE_PointerToint:
		return soap_out_PointerToint(soap, tag, id, (int *const*)ptr, "xsd:int");
	case SOAP_TYPE_PointerTopmns1__pmConnexionResponse:
		return soap_out_PointerTopmns1__pmConnexionResponse(soap, tag, id, (struct pmns1__pmConnexionResponse *const*)ptr, "pmns1:pmConnexionResponse");
	case SOAP_TYPE_PointerTopmns1__Ligne:
		return soap_out_PointerTopmns1__Ligne(soap, tag, id, (struct pmns1__Ligne *const*)ptr, "pmns1:Ligne");
	case SOAP_TYPE_PointerTostring:
		return soap_out_PointerTostring(soap, tag, id, (char **const*)ptr, "xsd:string");
	case SOAP_TYPE__QName:
		return soap_out_string(soap, "QName", id, (char**)&ptr, NULL);
	case SOAP_TYPE_string:
		return soap_out_string(soap, tag, id, (char**)&ptr, "xsd:string");
	}
	return SOAP_OK;
}
#endif

#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap *soap, const void *ptr, int type)
{
	(void)soap; (void)ptr; (void)type; /* appease -Wall -Werror */
	switch (type)
	{
	case SOAP_TYPE_pmns1__pmCalcul:
		soap_serialize_pmns1__pmCalcul(soap, (const struct pmns1__pmCalcul *)ptr);
		break;
	case SOAP_TYPE_pmns1__pmCalculResponse:
		soap_serialize_pmns1__pmCalculResponse(soap, (const struct pmns1__pmCalculResponse *)ptr);
		break;
	case SOAP_TYPE_pmns1__pmUpdate:
		soap_serialize_pmns1__pmUpdate(soap, (const struct pmns1__pmUpdate *)ptr);
		break;
	case SOAP_TYPE_pmns1__pmUpdateResponse:
		soap_serialize_pmns1__pmUpdateResponse(soap, (const struct pmns1__pmUpdateResponse *)ptr);
		break;
	case SOAP_TYPE_pmns1__pmSelect:
		soap_serialize_pmns1__pmSelect(soap, (const struct pmns1__pmSelect *)ptr);
		break;
	case SOAP_TYPE_pmns1__pmSelectResponse:
		soap_serialize_pmns1__pmSelectResponse(soap, (const struct pmns1__pmSelectResponse *)ptr);
		break;
	case SOAP_TYPE_pmns1__pmDeconnexion:
		soap_serialize_pmns1__pmDeconnexion(soap, (const struct pmns1__pmDeconnexion *)ptr);
		break;
	case SOAP_TYPE_pmns1__pmDeconnexionResponse:
		soap_serialize_pmns1__pmDeconnexionResponse(soap, (const struct pmns1__pmDeconnexionResponse *)ptr);
		break;
	case SOAP_TYPE_pmns1__pmConnexion:
		soap_serialize_pmns1__pmConnexion(soap, (const struct pmns1__pmConnexion *)ptr);
		break;
	case SOAP_TYPE_pmns1__pmConnexionResponse:
		soap_serialize_pmns1__pmConnexionResponse(soap, (const struct pmns1__pmConnexionResponse *)ptr);
		break;
	case SOAP_TYPE_pmns1__Resultat:
		soap_serialize_pmns1__Resultat(soap, (const struct pmns1__Resultat *)ptr);
		break;
	case SOAP_TYPE_pmns1__Ligne:
		soap_serialize_pmns1__Ligne(soap, (const struct pmns1__Ligne *)ptr);
		break;
	case SOAP_TYPE_PointerTodouble:
		soap_serialize_PointerTodouble(soap, (double *const*)ptr);
		break;
	case SOAP_TYPE_PointerTopmns1__pmSelectResponse:
		soap_serialize_PointerTopmns1__pmSelectResponse(soap, (struct pmns1__pmSelectResponse *const*)ptr);
		break;
	case SOAP_TYPE_PointerTopmns1__Resultat:
		soap_serialize_PointerTopmns1__Resultat(soap, (struct pmns1__Resultat *const*)ptr);
		break;
	case SOAP_TYPE_PointerToint:
		soap_serialize_PointerToint(soap, (int *const*)ptr);
		break;
	case SOAP_TYPE_PointerTopmns1__pmConnexionResponse:
		soap_serialize_PointerTopmns1__pmConnexionResponse(soap, (struct pmns1__pmConnexionResponse *const*)ptr);
		break;
	case SOAP_TYPE_PointerTopmns1__Ligne:
		soap_serialize_PointerTopmns1__Ligne(soap, (struct pmns1__Ligne *const*)ptr);
		break;
	case SOAP_TYPE_PointerTostring:
		soap_serialize_PointerTostring(soap, (char **const*)ptr);
		break;
	case SOAP_TYPE__QName:
		soap_serialize_string(soap, (char**)&ptr);
		break;
	case SOAP_TYPE_string:
		soap_serialize_string(soap, (char**)&ptr);
		break;
	}
}
#endif

SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap *soap, char *a)
{	(void)soap; /* appease -Wall -Werror */
#ifdef SOAP_DEFAULT_byte
	*a = SOAP_DEFAULT_byte;
#else
	*a = (char)0;
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap *soap, const char *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_byte);
	if (soap_out_byte(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap *soap, const char *tag, int id, const char *a, const char *type)
{
	return soap_outbyte(soap, tag, id, a, type, SOAP_TYPE_byte);
}

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap *soap, char *p, const char *tag, const char *type)
{
	if ((p = soap_in_byte(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap *soap, const char *tag, char *a, const char *type)
{
	return soap_inbyte(soap, tag, a, type, SOAP_TYPE_byte);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__Identifiant(struct soap *soap, int *a)
{	soap_default_int(soap, a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__Identifiant(struct soap *soap, const int *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_pmns1__Identifiant);
	if (soap_out_pmns1__Identifiant(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__Identifiant(struct soap *soap, const char *tag, int id, const int *a, const char *type)
{
	return soap_outint(soap, tag, id, a, type, SOAP_TYPE_pmns1__Identifiant);
}

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_pmns1__Identifiant(struct soap *soap, int *p, const char *tag, const char *type)
{
	if ((p = soap_in_pmns1__Identifiant(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 int * SOAP_FMAC4 soap_in_pmns1__Identifiant(struct soap *soap, const char *tag, int *a, const char *type)
{
	return soap_inint(soap, tag, a, type, SOAP_TYPE_pmns1__Identifiant);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap *soap, int *a)
{	(void)soap; /* appease -Wall -Werror */
#ifdef SOAP_DEFAULT_int
	*a = SOAP_DEFAULT_int;
#else
	*a = (int)0;
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap *soap, const int *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_int);
	if (soap_out_int(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap *soap, const char *tag, int id, const int *a, const char *type)
{
	return soap_outint(soap, tag, id, a, type, SOAP_TYPE_int);
}

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap *soap, int *p, const char *tag, const char *type)
{
	if ((p = soap_in_int(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap *soap, const char *tag, int *a, const char *type)
{
	return soap_inint(soap, tag, a, type, SOAP_TYPE_int);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap *soap, double *a)
{	(void)soap; /* appease -Wall -Werror */
#ifdef SOAP_DEFAULT_double
	*a = SOAP_DEFAULT_double;
#else
	*a = (double)0;
#endif
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap *soap, const double *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_double);
	if (soap_out_double(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap *soap, const char *tag, int id, const double *a, const char *type)
{
	return soap_outdouble(soap, tag, id, a, type, SOAP_TYPE_double);
}

SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap *soap, double *p, const char *tag, const char *type)
{
	if ((p = soap_in_double(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap *soap, const char *tag, double *a, const char *type)
{
	return soap_indouble(soap, tag, a, type, SOAP_TYPE_double);
}

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap *soap, const struct SOAP_ENV__Fault *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize__QName(soap, &a->faultcode);
	soap_serialize_string(soap, &a->faultstring);
	soap_serialize_string(soap, &a->faultactor);
	soap_serialize_PointerToSOAP_ENV__Detail(soap, &a->detail);
	soap_serialize_PointerToSOAP_ENV__Code(soap, &a->SOAP_ENV__Code);
	soap_serialize_PointerToSOAP_ENV__Reason(soap, &a->SOAP_ENV__Reason);
	soap_serialize_string(soap, &a->SOAP_ENV__Node);
	soap_serialize_string(soap, &a->SOAP_ENV__Role);
	soap_serialize_PointerToSOAP_ENV__Detail(soap, &a->SOAP_ENV__Detail);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default__QName(soap, &a->faultcode);
	soap_default_string(soap, &a->faultstring);
	soap_default_string(soap, &a->faultactor);
	a->detail = NULL;
	a->SOAP_ENV__Code = NULL;
	a->SOAP_ENV__Reason = NULL;
	soap_default_string(soap, &a->SOAP_ENV__Node);
	soap_default_string(soap, &a->SOAP_ENV__Role);
	a->SOAP_ENV__Detail = NULL;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap *soap, const struct SOAP_ENV__Fault *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_SOAP_ENV__Fault);
	if (soap_out_SOAP_ENV__Fault(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Fault *a, const char *type)
{
	const char *soap_tmp_faultcode = soap_QName2s(soap, a->faultcode);
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Fault), type);
	soap_out__QName(soap, "faultcode", -1, (char*const*)&soap_tmp_faultcode, "");
	soap_out_string(soap, "faultstring", -1, &a->faultstring, "xsd:string");
	soap_out_string(soap, "faultactor", -1, &a->faultactor, "xsd:string");
	soap_out_PointerToSOAP_ENV__Detail(soap, "detail", -1, &a->detail, "");
	soap_out_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Code", -1, &a->SOAP_ENV__Code, "");
	soap_out_PointerToSOAP_ENV__Reason(soap, "SOAP-ENV:Reason", -1, &a->SOAP_ENV__Reason, "");
	soap_out_string(soap, "SOAP-ENV:Node", -1, &a->SOAP_ENV__Node, "");
	soap_out_string(soap, "SOAP-ENV:Role", -1, &a->SOAP_ENV__Role, "");
	soap_out_PointerToSOAP_ENV__Detail(soap, "SOAP-ENV:Detail", -1, &a->SOAP_ENV__Detail, "");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Fault(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap *soap, const char *tag, struct SOAP_ENV__Fault *a, const char *type)
{
	short soap_flag_faultcode = 1, soap_flag_faultstring = 1, soap_flag_faultactor = 1, soap_flag_detail = 1, soap_flag_SOAP_ENV__Code = 1, soap_flag_SOAP_ENV__Reason = 1, soap_flag_SOAP_ENV__Node = 1, soap_flag_SOAP_ENV__Role = 1, soap_flag_SOAP_ENV__Detail = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct SOAP_ENV__Fault *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Fault, sizeof(struct SOAP_ENV__Fault), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Fault(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_faultcode && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in__QName(soap, "faultcode", &a->faultcode, ""))
				{	soap_flag_faultcode--;
					continue;
				}
			if (soap_flag_faultstring && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "faultstring", &a->faultstring, "xsd:string"))
				{	soap_flag_faultstring--;
					continue;
				}
			if (soap_flag_faultactor && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "faultactor", &a->faultactor, "xsd:string"))
				{	soap_flag_faultactor--;
					continue;
				}
			if (soap_flag_detail && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToSOAP_ENV__Detail(soap, "detail", &a->detail, ""))
				{	soap_flag_detail--;
					continue;
				}
			if (soap_flag_SOAP_ENV__Code && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Code", &a->SOAP_ENV__Code, ""))
				{	soap_flag_SOAP_ENV__Code--;
					continue;
				}
			if (soap_flag_SOAP_ENV__Reason && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToSOAP_ENV__Reason(soap, "SOAP-ENV:Reason", &a->SOAP_ENV__Reason, ""))
				{	soap_flag_SOAP_ENV__Reason--;
					continue;
				}
			if (soap_flag_SOAP_ENV__Node && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "SOAP-ENV:Node", &a->SOAP_ENV__Node, "xsd:string"))
				{	soap_flag_SOAP_ENV__Node--;
					continue;
				}
			if (soap_flag_SOAP_ENV__Role && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "SOAP-ENV:Role", &a->SOAP_ENV__Role, "xsd:string"))
				{	soap_flag_SOAP_ENV__Role--;
					continue;
				}
			if (soap_flag_SOAP_ENV__Detail && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToSOAP_ENV__Detail(soap, "SOAP-ENV:Detail", &a->SOAP_ENV__Detail, ""))
				{	soap_flag_SOAP_ENV__Detail--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Fault *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_SOAP_ENV__Fault, 0, sizeof(struct SOAP_ENV__Fault), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap *soap, const struct SOAP_ENV__Reason *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_string(soap, &a->SOAP_ENV__Text);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_string(soap, &a->SOAP_ENV__Text);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap *soap, const struct SOAP_ENV__Reason *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_SOAP_ENV__Reason);
	if (soap_out_SOAP_ENV__Reason(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Reason *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Reason), type);
	soap_out_string(soap, "SOAP-ENV:Text", -1, &a->SOAP_ENV__Text, "");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Reason(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap *soap, const char *tag, struct SOAP_ENV__Reason *a, const char *type)
{
	short soap_flag_SOAP_ENV__Text = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct SOAP_ENV__Reason *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Reason, sizeof(struct SOAP_ENV__Reason), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Reason(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_SOAP_ENV__Text && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "SOAP-ENV:Text", &a->SOAP_ENV__Text, "xsd:string"))
				{	soap_flag_SOAP_ENV__Text--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Reason *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_SOAP_ENV__Reason, 0, sizeof(struct SOAP_ENV__Reason), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap *soap, const struct SOAP_ENV__Detail *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_markelement(soap, a->fault, a->__type);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->__type = 0;
	a->fault = NULL;
	a->__any = NULL;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap *soap, const struct SOAP_ENV__Detail *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_SOAP_ENV__Detail);
	if (soap_out_SOAP_ENV__Detail(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Detail *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Detail), type);
	soap_putelement(soap, a->fault, "fault", -1, a->__type);
	soap_outliteral(soap, "-any", &a->__any);
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Detail(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap *soap, const char *tag, struct SOAP_ENV__Detail *a, const char *type)
{
	short soap_flag_fault = 1, soap_flag___any = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct SOAP_ENV__Detail *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Detail, sizeof(struct SOAP_ENV__Detail), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Detail(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_fault && soap->error == SOAP_TAG_MISMATCH)
				if ((a->fault = soap_getelement(soap, &a->__type)))
				{	soap_flag_fault = 0;
					continue;
				}
			if (soap_flag___any && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_inliteral(soap, "-any", &a->__any))
				{	soap_flag___any--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Detail *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_SOAP_ENV__Detail, 0, sizeof(struct SOAP_ENV__Detail), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap *soap, const struct SOAP_ENV__Code *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize__QName(soap, &a->SOAP_ENV__Value);
	soap_serialize_PointerToSOAP_ENV__Code(soap, &a->SOAP_ENV__Subcode);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default__QName(soap, &a->SOAP_ENV__Value);
	a->SOAP_ENV__Subcode = NULL;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap *soap, const struct SOAP_ENV__Code *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_SOAP_ENV__Code);
	if (soap_out_SOAP_ENV__Code(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Code *a, const char *type)
{
	const char *soap_tmp_SOAP_ENV__Value = soap_QName2s(soap, a->SOAP_ENV__Value);
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Code), type);
	soap_out__QName(soap, "SOAP-ENV:Value", -1, (char*const*)&soap_tmp_SOAP_ENV__Value, "");
	soap_out_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Subcode", -1, &a->SOAP_ENV__Subcode, "");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Code(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap *soap, const char *tag, struct SOAP_ENV__Code *a, const char *type)
{
	short soap_flag_SOAP_ENV__Value = 1, soap_flag_SOAP_ENV__Subcode = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct SOAP_ENV__Code *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Code, sizeof(struct SOAP_ENV__Code), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Code(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_SOAP_ENV__Value && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in__QName(soap, "SOAP-ENV:Value", &a->SOAP_ENV__Value, ""))
				{	soap_flag_SOAP_ENV__Value--;
					continue;
				}
			if (soap_flag_SOAP_ENV__Subcode && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToSOAP_ENV__Code(soap, "SOAP-ENV:Subcode", &a->SOAP_ENV__Subcode, ""))
				{	soap_flag_SOAP_ENV__Subcode--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Code *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_SOAP_ENV__Code, 0, sizeof(struct SOAP_ENV__Code), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap *soap, const struct SOAP_ENV__Header *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	/* transient dummy skipped */
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	/* transient dummy skipped */
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap *soap, const struct SOAP_ENV__Header *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_SOAP_ENV__Header);
	if (soap_out_SOAP_ENV__Header(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Header *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_SOAP_ENV__Header), type);
	/* transient dummy skipped */
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p, const char *tag, const char *type)
{
	if ((p = soap_in_SOAP_ENV__Header(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap *soap, const char *tag, struct SOAP_ENV__Header *a, const char *type)
{;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct SOAP_ENV__Header *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_SOAP_ENV__Header, sizeof(struct SOAP_ENV__Header), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_SOAP_ENV__Header(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
		/* transient dummy skipped */
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Header *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_SOAP_ENV__Header, 0, sizeof(struct SOAP_ENV__Header), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

#endif

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmCalcul(struct soap *soap, const struct pmns1__pmCalcul *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_embedded(soap, &a->taux, SOAP_TYPE_double);
	soap_embedded(soap, &a->nb, SOAP_TYPE_int);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmCalcul(struct soap *soap, struct pmns1__pmCalcul *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_double(soap, &a->taux);
	soap_default_int(soap, &a->nb);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmCalcul(struct soap *soap, const struct pmns1__pmCalcul *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_pmns1__pmCalcul);
	if (soap_out_pmns1__pmCalcul(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmCalcul(struct soap *soap, const char *tag, int id, const struct pmns1__pmCalcul *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_pmns1__pmCalcul), type);
	soap_out_double(soap, "taux", -1, &a->taux, "xsd:double");
	soap_out_int(soap, "nb", -1, &a->nb, "xsd:int");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct pmns1__pmCalcul * SOAP_FMAC4 soap_get_pmns1__pmCalcul(struct soap *soap, struct pmns1__pmCalcul *p, const char *tag, const char *type)
{
	if ((p = soap_in_pmns1__pmCalcul(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__pmCalcul * SOAP_FMAC4 soap_in_pmns1__pmCalcul(struct soap *soap, const char *tag, struct pmns1__pmCalcul *a, const char *type)
{
	short soap_flag_taux = 1, soap_flag_nb = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct pmns1__pmCalcul *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_pmns1__pmCalcul, sizeof(struct pmns1__pmCalcul), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_pmns1__pmCalcul(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_taux && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_double(soap, "taux", &a->taux, "xsd:double"))
				{	soap_flag_taux--;
					continue;
				}
			if (soap_flag_nb && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_int(soap, "nb", &a->nb, "xsd:int"))
				{	soap_flag_nb--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if ((soap->mode & SOAP_XML_STRICT) && (soap_flag_taux > 0 || soap_flag_nb > 0))
		{	soap->error = SOAP_OCCURS;
			return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct pmns1__pmCalcul *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_pmns1__pmCalcul, 0, sizeof(struct pmns1__pmCalcul), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmCalculResponse(struct soap *soap, const struct pmns1__pmCalculResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_PointerTodouble(soap, &a->return_);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmCalculResponse(struct soap *soap, struct pmns1__pmCalculResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->return_ = NULL;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmCalculResponse(struct soap *soap, const struct pmns1__pmCalculResponse *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_pmns1__pmCalculResponse);
	if (soap_out_pmns1__pmCalculResponse(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmCalculResponse(struct soap *soap, const char *tag, int id, const struct pmns1__pmCalculResponse *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_pmns1__pmCalculResponse), type);
	if (a->return_)
		soap_element_result(soap, "return");
	soap_out_PointerTodouble(soap, "return", -1, &a->return_, "xsd:double");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct pmns1__pmCalculResponse * SOAP_FMAC4 soap_get_pmns1__pmCalculResponse(struct soap *soap, struct pmns1__pmCalculResponse *p, const char *tag, const char *type)
{
	if ((p = soap_in_pmns1__pmCalculResponse(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__pmCalculResponse * SOAP_FMAC4 soap_in_pmns1__pmCalculResponse(struct soap *soap, const char *tag, struct pmns1__pmCalculResponse *a, const char *type)
{
	short soap_flag_return_ = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct pmns1__pmCalculResponse *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_pmns1__pmCalculResponse, sizeof(struct pmns1__pmCalculResponse), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_pmns1__pmCalculResponse(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_return_ && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerTodouble(soap, "return", &a->return_, "xsd:double"))
				{	soap_flag_return_--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct pmns1__pmCalculResponse *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_pmns1__pmCalculResponse, 0, sizeof(struct pmns1__pmCalculResponse), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmUpdate(struct soap *soap, const struct pmns1__pmUpdate *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_string(soap, &a->query);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmUpdate(struct soap *soap, struct pmns1__pmUpdate *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_pmns1__Identifiant(soap, &a->id);
	soap_default_string(soap, &a->query);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmUpdate(struct soap *soap, const struct pmns1__pmUpdate *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_pmns1__pmUpdate);
	if (soap_out_pmns1__pmUpdate(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmUpdate(struct soap *soap, const char *tag, int id, const struct pmns1__pmUpdate *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_pmns1__pmUpdate), type);
	soap_out_pmns1__Identifiant(soap, "id", -1, &a->id, "pmns1:Identifiant");
	soap_out_string(soap, "query", -1, &a->query, "xsd:string");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct pmns1__pmUpdate * SOAP_FMAC4 soap_get_pmns1__pmUpdate(struct soap *soap, struct pmns1__pmUpdate *p, const char *tag, const char *type)
{
	if ((p = soap_in_pmns1__pmUpdate(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__pmUpdate * SOAP_FMAC4 soap_in_pmns1__pmUpdate(struct soap *soap, const char *tag, struct pmns1__pmUpdate *a, const char *type)
{
	short soap_flag_id = 1, soap_flag_query = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct pmns1__pmUpdate *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_pmns1__pmUpdate, sizeof(struct pmns1__pmUpdate), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_pmns1__pmUpdate(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_id && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_pmns1__Identifiant(soap, "id", &a->id, "pmns1:Identifiant"))
				{	soap_flag_id--;
					continue;
				}
			if (soap_flag_query && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "query", &a->query, "xsd:string"))
				{	soap_flag_query--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if ((soap->mode & SOAP_XML_STRICT) && (soap_flag_id > 0))
		{	soap->error = SOAP_OCCURS;
			return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct pmns1__pmUpdate *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_pmns1__pmUpdate, 0, sizeof(struct pmns1__pmUpdate), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmUpdateResponse(struct soap *soap, const struct pmns1__pmUpdateResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_PointerToint(soap, &a->resultat);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmUpdateResponse(struct soap *soap, struct pmns1__pmUpdateResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->resultat = NULL;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmUpdateResponse(struct soap *soap, const struct pmns1__pmUpdateResponse *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_pmns1__pmUpdateResponse);
	if (soap_out_pmns1__pmUpdateResponse(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmUpdateResponse(struct soap *soap, const char *tag, int id, const struct pmns1__pmUpdateResponse *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_pmns1__pmUpdateResponse), type);
	if (a->resultat)
		soap_element_result(soap, "resultat");
	soap_out_PointerToint(soap, "resultat", -1, &a->resultat, "xsd:int");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct pmns1__pmUpdateResponse * SOAP_FMAC4 soap_get_pmns1__pmUpdateResponse(struct soap *soap, struct pmns1__pmUpdateResponse *p, const char *tag, const char *type)
{
	if ((p = soap_in_pmns1__pmUpdateResponse(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__pmUpdateResponse * SOAP_FMAC4 soap_in_pmns1__pmUpdateResponse(struct soap *soap, const char *tag, struct pmns1__pmUpdateResponse *a, const char *type)
{
	short soap_flag_resultat = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct pmns1__pmUpdateResponse *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_pmns1__pmUpdateResponse, sizeof(struct pmns1__pmUpdateResponse), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_pmns1__pmUpdateResponse(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_resultat && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToint(soap, "resultat", &a->resultat, "xsd:int"))
				{	soap_flag_resultat--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct pmns1__pmUpdateResponse *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_pmns1__pmUpdateResponse, 0, sizeof(struct pmns1__pmUpdateResponse), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmSelect(struct soap *soap, const struct pmns1__pmSelect *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_string(soap, &a->query);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmSelect(struct soap *soap, struct pmns1__pmSelect *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_pmns1__Identifiant(soap, &a->id);
	soap_default_string(soap, &a->query);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmSelect(struct soap *soap, const struct pmns1__pmSelect *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_pmns1__pmSelect);
	if (soap_out_pmns1__pmSelect(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmSelect(struct soap *soap, const char *tag, int id, const struct pmns1__pmSelect *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_pmns1__pmSelect), type);
	soap_out_pmns1__Identifiant(soap, "id", -1, &a->id, "pmns1:Identifiant");
	soap_out_string(soap, "query", -1, &a->query, "xsd:string");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct pmns1__pmSelect * SOAP_FMAC4 soap_get_pmns1__pmSelect(struct soap *soap, struct pmns1__pmSelect *p, const char *tag, const char *type)
{
	if ((p = soap_in_pmns1__pmSelect(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__pmSelect * SOAP_FMAC4 soap_in_pmns1__pmSelect(struct soap *soap, const char *tag, struct pmns1__pmSelect *a, const char *type)
{
	short soap_flag_id = 1, soap_flag_query = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct pmns1__pmSelect *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_pmns1__pmSelect, sizeof(struct pmns1__pmSelect), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_pmns1__pmSelect(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_id && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_pmns1__Identifiant(soap, "id", &a->id, "pmns1:Identifiant"))
				{	soap_flag_id--;
					continue;
				}
			if (soap_flag_query && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "query", &a->query, "xsd:string"))
				{	soap_flag_query--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if ((soap->mode & SOAP_XML_STRICT) && (soap_flag_id > 0))
		{	soap->error = SOAP_OCCURS;
			return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct pmns1__pmSelect *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_pmns1__pmSelect, 0, sizeof(struct pmns1__pmSelect), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmSelectResponse(struct soap *soap, const struct pmns1__pmSelectResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_PointerTopmns1__Resultat(soap, &a->resultat);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmSelectResponse(struct soap *soap, struct pmns1__pmSelectResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->resultat = NULL;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmSelectResponse(struct soap *soap, const struct pmns1__pmSelectResponse *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_pmns1__pmSelectResponse);
	if (soap_out_pmns1__pmSelectResponse(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmSelectResponse(struct soap *soap, const char *tag, int id, const struct pmns1__pmSelectResponse *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_pmns1__pmSelectResponse), type);
	if (a->resultat)
		soap_element_result(soap, "resultat");
	soap_out_PointerTopmns1__Resultat(soap, "resultat", -1, &a->resultat, "pmns1:Resultat");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct pmns1__pmSelectResponse * SOAP_FMAC4 soap_get_pmns1__pmSelectResponse(struct soap *soap, struct pmns1__pmSelectResponse *p, const char *tag, const char *type)
{
	if ((p = soap_in_pmns1__pmSelectResponse(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__pmSelectResponse * SOAP_FMAC4 soap_in_pmns1__pmSelectResponse(struct soap *soap, const char *tag, struct pmns1__pmSelectResponse *a, const char *type)
{
	short soap_flag_resultat = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct pmns1__pmSelectResponse *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_pmns1__pmSelectResponse, sizeof(struct pmns1__pmSelectResponse), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_pmns1__pmSelectResponse(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_resultat && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerTopmns1__Resultat(soap, "resultat", &a->resultat, "pmns1:Resultat"))
				{	soap_flag_resultat--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct pmns1__pmSelectResponse *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_pmns1__pmSelectResponse, 0, sizeof(struct pmns1__pmSelectResponse), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmDeconnexion(struct soap *soap, const struct pmns1__pmDeconnexion *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmDeconnexion(struct soap *soap, struct pmns1__pmDeconnexion *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_pmns1__Identifiant(soap, &a->id);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmDeconnexion(struct soap *soap, const struct pmns1__pmDeconnexion *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_pmns1__pmDeconnexion);
	if (soap_out_pmns1__pmDeconnexion(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmDeconnexion(struct soap *soap, const char *tag, int id, const struct pmns1__pmDeconnexion *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_pmns1__pmDeconnexion), type);
	soap_out_pmns1__Identifiant(soap, "id", -1, &a->id, "pmns1:Identifiant");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct pmns1__pmDeconnexion * SOAP_FMAC4 soap_get_pmns1__pmDeconnexion(struct soap *soap, struct pmns1__pmDeconnexion *p, const char *tag, const char *type)
{
	if ((p = soap_in_pmns1__pmDeconnexion(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__pmDeconnexion * SOAP_FMAC4 soap_in_pmns1__pmDeconnexion(struct soap *soap, const char *tag, struct pmns1__pmDeconnexion *a, const char *type)
{
	short soap_flag_id = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct pmns1__pmDeconnexion *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_pmns1__pmDeconnexion, sizeof(struct pmns1__pmDeconnexion), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_pmns1__pmDeconnexion(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_id && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_pmns1__Identifiant(soap, "id", &a->id, "pmns1:Identifiant"))
				{	soap_flag_id--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if ((soap->mode & SOAP_XML_STRICT) && (soap_flag_id > 0))
		{	soap->error = SOAP_OCCURS;
			return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct pmns1__pmDeconnexion *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_pmns1__pmDeconnexion, 0, sizeof(struct pmns1__pmDeconnexion), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmDeconnexionResponse(struct soap *soap, const struct pmns1__pmDeconnexionResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_PointerToint(soap, &a->resultat);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmDeconnexionResponse(struct soap *soap, struct pmns1__pmDeconnexionResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->resultat = NULL;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmDeconnexionResponse(struct soap *soap, const struct pmns1__pmDeconnexionResponse *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_pmns1__pmDeconnexionResponse);
	if (soap_out_pmns1__pmDeconnexionResponse(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmDeconnexionResponse(struct soap *soap, const char *tag, int id, const struct pmns1__pmDeconnexionResponse *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_pmns1__pmDeconnexionResponse), type);
	if (a->resultat)
		soap_element_result(soap, "resultat");
	soap_out_PointerToint(soap, "resultat", -1, &a->resultat, "xsd:int");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct pmns1__pmDeconnexionResponse * SOAP_FMAC4 soap_get_pmns1__pmDeconnexionResponse(struct soap *soap, struct pmns1__pmDeconnexionResponse *p, const char *tag, const char *type)
{
	if ((p = soap_in_pmns1__pmDeconnexionResponse(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__pmDeconnexionResponse * SOAP_FMAC4 soap_in_pmns1__pmDeconnexionResponse(struct soap *soap, const char *tag, struct pmns1__pmDeconnexionResponse *a, const char *type)
{
	short soap_flag_resultat = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct pmns1__pmDeconnexionResponse *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_pmns1__pmDeconnexionResponse, sizeof(struct pmns1__pmDeconnexionResponse), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_pmns1__pmDeconnexionResponse(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_resultat && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_PointerToint(soap, "resultat", &a->resultat, "xsd:int"))
				{	soap_flag_resultat--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct pmns1__pmDeconnexionResponse *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_pmns1__pmDeconnexionResponse, 0, sizeof(struct pmns1__pmDeconnexionResponse), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmConnexion(struct soap *soap, const struct pmns1__pmConnexion *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_serialize_string(soap, &a->login);
	soap_serialize_string(soap, &a->password);
	soap_serialize_string(soap, &a->database);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmConnexion(struct soap *soap, struct pmns1__pmConnexion *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_string(soap, &a->login);
	soap_default_string(soap, &a->password);
	soap_default_string(soap, &a->database);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmConnexion(struct soap *soap, const struct pmns1__pmConnexion *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_pmns1__pmConnexion);
	if (soap_out_pmns1__pmConnexion(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmConnexion(struct soap *soap, const char *tag, int id, const struct pmns1__pmConnexion *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_pmns1__pmConnexion), type);
	soap_out_string(soap, "login", -1, &a->login, "xsd:string");
	soap_out_string(soap, "password", -1, &a->password, "xsd:string");
	soap_out_string(soap, "database", -1, &a->database, "xsd:string");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct pmns1__pmConnexion * SOAP_FMAC4 soap_get_pmns1__pmConnexion(struct soap *soap, struct pmns1__pmConnexion *p, const char *tag, const char *type)
{
	if ((p = soap_in_pmns1__pmConnexion(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__pmConnexion * SOAP_FMAC4 soap_in_pmns1__pmConnexion(struct soap *soap, const char *tag, struct pmns1__pmConnexion *a, const char *type)
{
	short soap_flag_login = 1, soap_flag_password = 1, soap_flag_database = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct pmns1__pmConnexion *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_pmns1__pmConnexion, sizeof(struct pmns1__pmConnexion), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_pmns1__pmConnexion(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_login && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "login", &a->login, "xsd:string"))
				{	soap_flag_login--;
					continue;
				}
			if (soap_flag_password && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "password", &a->password, "xsd:string"))
				{	soap_flag_password--;
					continue;
				}
			if (soap_flag_database && (soap->error == SOAP_TAG_MISMATCH || soap->error == SOAP_NO_TAG))
				if (soap_in_string(soap, "database", &a->database, "xsd:string"))
				{	soap_flag_database--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct pmns1__pmConnexion *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_pmns1__pmConnexion, 0, sizeof(struct pmns1__pmConnexion), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmConnexionResponse(struct soap *soap, const struct pmns1__pmConnexionResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmConnexionResponse(struct soap *soap, struct pmns1__pmConnexionResponse *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	soap_default_pmns1__Identifiant(soap, &a->id);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmConnexionResponse(struct soap *soap, const struct pmns1__pmConnexionResponse *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_pmns1__pmConnexionResponse);
	if (soap_out_pmns1__pmConnexionResponse(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmConnexionResponse(struct soap *soap, const char *tag, int id, const struct pmns1__pmConnexionResponse *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_pmns1__pmConnexionResponse), type);
	soap_element_result(soap, "id");
	soap_out_pmns1__Identifiant(soap, "id", -1, &a->id, "pmns1:Identifiant");
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct pmns1__pmConnexionResponse * SOAP_FMAC4 soap_get_pmns1__pmConnexionResponse(struct soap *soap, struct pmns1__pmConnexionResponse *p, const char *tag, const char *type)
{
	if ((p = soap_in_pmns1__pmConnexionResponse(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__pmConnexionResponse * SOAP_FMAC4 soap_in_pmns1__pmConnexionResponse(struct soap *soap, const char *tag, struct pmns1__pmConnexionResponse *a, const char *type)
{
	short soap_flag_id = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct pmns1__pmConnexionResponse *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_pmns1__pmConnexionResponse, sizeof(struct pmns1__pmConnexionResponse), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_pmns1__pmConnexionResponse(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_id && soap->error == SOAP_TAG_MISMATCH)
				if (soap_in_pmns1__Identifiant(soap, "id", &a->id, "pmns1:Identifiant"))
				{	soap_flag_id--;
					continue;
				}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if ((soap->mode & SOAP_XML_STRICT) && (soap_flag_id > 0))
		{	soap->error = SOAP_OCCURS;
			return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct pmns1__pmConnexionResponse *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_pmns1__pmConnexionResponse, 0, sizeof(struct pmns1__pmConnexionResponse), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__Resultat(struct soap *soap, const struct pmns1__Resultat *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	if (a->lignes)
	{	int i;
		for (i = 0; i < a->__sizelignes; i++)
		{
			soap_embedded(soap, a->lignes + i, SOAP_TYPE_pmns1__Ligne);
			soap_serialize_pmns1__Ligne(soap, a->lignes + i);
		}
	}
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__Resultat(struct soap *soap, struct pmns1__Resultat *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->__sizelignes = 0;
	a->lignes = NULL;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__Resultat(struct soap *soap, const struct pmns1__Resultat *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_pmns1__Resultat);
	if (soap_out_pmns1__Resultat(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__Resultat(struct soap *soap, const char *tag, int id, const struct pmns1__Resultat *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_pmns1__Resultat), type);
	if (a->lignes)
	{	int i;
		for (i = 0; i < a->__sizelignes; i++)
			soap_out_pmns1__Ligne(soap, "lignes", -1, a->lignes + i, "pmns1:Ligne");
	}
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct pmns1__Resultat * SOAP_FMAC4 soap_get_pmns1__Resultat(struct soap *soap, struct pmns1__Resultat *p, const char *tag, const char *type)
{
	if ((p = soap_in_pmns1__Resultat(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__Resultat * SOAP_FMAC4 soap_in_pmns1__Resultat(struct soap *soap, const char *tag, struct pmns1__Resultat *a, const char *type)
{
	short soap_flag_lignes = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct pmns1__Resultat *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_pmns1__Resultat, sizeof(struct pmns1__Resultat), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_pmns1__Resultat(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_lignes && soap->error == SOAP_TAG_MISMATCH)
			{	struct pmns1__Ligne *p;
				soap_new_block(soap);
				for (a->__sizelignes = 0; !soap_element_begin_in(soap, "lignes", 1); a->__sizelignes++)
				{	p = (struct pmns1__Ligne *)soap_push_block(soap, sizeof(struct pmns1__Ligne));
					soap_default_pmns1__Ligne(soap, p);
					soap_revert(soap);
					if (!soap_in_pmns1__Ligne(soap, "lignes", p, "pmns1:Ligne"))
						break;
					soap_flag_lignes = 0;
				}
				a->lignes = (struct pmns1__Ligne *)soap_save_block(soap, NULL, 1);
				if (!soap_flag_lignes && soap->error == SOAP_TAG_MISMATCH)
					continue;
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct pmns1__Resultat *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_pmns1__Resultat, 0, sizeof(struct pmns1__Resultat), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__Ligne(struct soap *soap, const struct pmns1__Ligne *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	if (a->valeurs)
	{	int i;
		for (i = 0; i < a->__sizevaleurs; i++)
		{
			soap_serialize_string(soap, a->valeurs + i);
		}
	}
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__Ligne(struct soap *soap, struct pmns1__Ligne *a)
{
	(void)soap; (void)a; /* appease -Wall -Werror */
	a->__sizevaleurs = 0;
	a->valeurs = NULL;
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__Ligne(struct soap *soap, const struct pmns1__Ligne *a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_pmns1__Ligne);
	if (soap_out_pmns1__Ligne(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__Ligne(struct soap *soap, const char *tag, int id, const struct pmns1__Ligne *a, const char *type)
{
	soap_element_begin_out(soap, tag, soap_embedded_id(soap, id, a, SOAP_TYPE_pmns1__Ligne), type);
	if (a->valeurs)
	{	int i;
		for (i = 0; i < a->__sizevaleurs; i++)
			soap_out_string(soap, "valeurs", -1, a->valeurs + i, "xsd:string");
	}
	soap_element_end_out(soap, tag);
	return SOAP_OK;
}

SOAP_FMAC3 struct pmns1__Ligne * SOAP_FMAC4 soap_get_pmns1__Ligne(struct soap *soap, struct pmns1__Ligne *p, const char *tag, const char *type)
{
	if ((p = soap_in_pmns1__Ligne(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__Ligne * SOAP_FMAC4 soap_in_pmns1__Ligne(struct soap *soap, const char *tag, struct pmns1__Ligne *a, const char *type)
{
	short soap_flag_valeurs = 1;
	if (soap_element_begin_in(soap, tag, 0))
		return NULL;
	if (*soap->type && soap_match_tag(soap, soap->type, type))
	{	soap->error = SOAP_TYPE;
		return NULL;
	}
	a = (struct pmns1__Ligne *)soap_id_enter(soap, soap->id, a, SOAP_TYPE_pmns1__Ligne, sizeof(struct pmns1__Ligne), 0, NULL, NULL, NULL);
	if (!a)
		return NULL;
	soap_default_pmns1__Ligne(soap, a);
	if (soap->body && !*soap->href)
	{
		for (;;)
		{	soap->error = SOAP_TAG_MISMATCH;
			if (soap_flag_valeurs && soap->error == SOAP_TAG_MISMATCH)
			{	char **p;
				soap_new_block(soap);
				for (a->__sizevaleurs = 0; !soap_element_begin_in(soap, "valeurs", 1); a->__sizevaleurs++)
				{	p = (char **)soap_push_block(soap, sizeof(char *));
					*p = NULL;
					soap_revert(soap);
					if (!soap_in_string(soap, "valeurs", p, "xsd:string"))
						break;
					soap_flag_valeurs = 0;
				}
				a->valeurs = (char **)soap_save_block(soap, NULL, 1);
				if (!soap_flag_valeurs && soap->error == SOAP_TAG_MISMATCH)
					continue;
			}
			if (soap->error == SOAP_TAG_MISMATCH)
				soap->error = soap_ignore_element(soap);
			if (soap->error == SOAP_NO_TAG)
				break;
			if (soap->error)
				return NULL;
		}
		if (soap_element_end_in(soap, tag))
			return NULL;
	}
	else
	{	a = (struct pmns1__Ligne *)soap_id_forward(soap, soap->href, (void**)a, 0, SOAP_TYPE_pmns1__Ligne, 0, sizeof(struct pmns1__Ligne), 0, NULL);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_SOAP_ENV__Reason))
		soap_serialize_SOAP_ENV__Reason(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerToSOAP_ENV__Reason);
	if (soap_out_PointerToSOAP_ENV__Reason(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap *soap, const char *tag, int id, struct SOAP_ENV__Reason *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_SOAP_ENV__Reason);
	if (id < 0)
		return soap->error;
	return soap_out_SOAP_ENV__Reason(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToSOAP_ENV__Reason(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap *soap, const char *tag, struct SOAP_ENV__Reason **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1))
		return NULL;
	if (!a)
		if (!(a = (struct SOAP_ENV__Reason **)soap_malloc(soap, sizeof(struct SOAP_ENV__Reason *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_SOAP_ENV__Reason(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Reason **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_SOAP_ENV__Reason, sizeof(struct SOAP_ENV__Reason), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_SOAP_ENV__Detail))
		soap_serialize_SOAP_ENV__Detail(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerToSOAP_ENV__Detail);
	if (soap_out_PointerToSOAP_ENV__Detail(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap *soap, const char *tag, int id, struct SOAP_ENV__Detail *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_SOAP_ENV__Detail);
	if (id < 0)
		return soap->error;
	return soap_out_SOAP_ENV__Detail(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToSOAP_ENV__Detail(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap *soap, const char *tag, struct SOAP_ENV__Detail **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1))
		return NULL;
	if (!a)
		if (!(a = (struct SOAP_ENV__Detail **)soap_malloc(soap, sizeof(struct SOAP_ENV__Detail *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_SOAP_ENV__Detail(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Detail **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_SOAP_ENV__Detail, sizeof(struct SOAP_ENV__Detail), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

#endif

#ifndef WITH_NOGLOBAL

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_SOAP_ENV__Code))
		soap_serialize_SOAP_ENV__Code(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerToSOAP_ENV__Code);
	if (soap_out_PointerToSOAP_ENV__Code(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap *soap, const char *tag, int id, struct SOAP_ENV__Code *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_SOAP_ENV__Code);
	if (id < 0)
		return soap->error;
	return soap_out_SOAP_ENV__Code(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToSOAP_ENV__Code(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap *soap, const char *tag, struct SOAP_ENV__Code **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1))
		return NULL;
	if (!a)
		if (!(a = (struct SOAP_ENV__Code **)soap_malloc(soap, sizeof(struct SOAP_ENV__Code *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_SOAP_ENV__Code(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct SOAP_ENV__Code **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_SOAP_ENV__Code, sizeof(struct SOAP_ENV__Code), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

#endif

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTodouble(struct soap *soap, double *const*a)
{
	soap_reference(soap, *a, SOAP_TYPE_double);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTodouble(struct soap *soap, double *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerTodouble);
	if (soap_out_PointerTodouble(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTodouble(struct soap *soap, const char *tag, int id, double *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_double);
	if (id < 0)
		return soap->error;
	return soap_out_double(soap, tag, id, *a, type);
}

SOAP_FMAC3 double ** SOAP_FMAC4 soap_get_PointerTodouble(struct soap *soap, double **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTodouble(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 double ** SOAP_FMAC4 soap_in_PointerTodouble(struct soap *soap, const char *tag, double **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1))
		return NULL;
	if (!a)
		if (!(a = (double **)soap_malloc(soap, sizeof(double *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_double(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (double **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_double, sizeof(double), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTopmns1__pmSelectResponse(struct soap *soap, struct pmns1__pmSelectResponse *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_pmns1__pmSelectResponse))
		soap_serialize_pmns1__pmSelectResponse(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTopmns1__pmSelectResponse(struct soap *soap, struct pmns1__pmSelectResponse *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerTopmns1__pmSelectResponse);
	if (soap_out_PointerTopmns1__pmSelectResponse(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTopmns1__pmSelectResponse(struct soap *soap, const char *tag, int id, struct pmns1__pmSelectResponse *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_pmns1__pmSelectResponse);
	if (id < 0)
		return soap->error;
	return soap_out_pmns1__pmSelectResponse(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct pmns1__pmSelectResponse ** SOAP_FMAC4 soap_get_PointerTopmns1__pmSelectResponse(struct soap *soap, struct pmns1__pmSelectResponse **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTopmns1__pmSelectResponse(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__pmSelectResponse ** SOAP_FMAC4 soap_in_PointerTopmns1__pmSelectResponse(struct soap *soap, const char *tag, struct pmns1__pmSelectResponse **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1))
		return NULL;
	if (!a)
		if (!(a = (struct pmns1__pmSelectResponse **)soap_malloc(soap, sizeof(struct pmns1__pmSelectResponse *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_pmns1__pmSelectResponse(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct pmns1__pmSelectResponse **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_pmns1__pmSelectResponse, sizeof(struct pmns1__pmSelectResponse), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTopmns1__Resultat(struct soap *soap, struct pmns1__Resultat *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_pmns1__Resultat))
		soap_serialize_pmns1__Resultat(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTopmns1__Resultat(struct soap *soap, struct pmns1__Resultat *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerTopmns1__Resultat);
	if (soap_out_PointerTopmns1__Resultat(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTopmns1__Resultat(struct soap *soap, const char *tag, int id, struct pmns1__Resultat *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_pmns1__Resultat);
	if (id < 0)
		return soap->error;
	return soap_out_pmns1__Resultat(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct pmns1__Resultat ** SOAP_FMAC4 soap_get_PointerTopmns1__Resultat(struct soap *soap, struct pmns1__Resultat **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTopmns1__Resultat(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__Resultat ** SOAP_FMAC4 soap_in_PointerTopmns1__Resultat(struct soap *soap, const char *tag, struct pmns1__Resultat **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1))
		return NULL;
	if (!a)
		if (!(a = (struct pmns1__Resultat **)soap_malloc(soap, sizeof(struct pmns1__Resultat *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_pmns1__Resultat(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct pmns1__Resultat **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_pmns1__Resultat, sizeof(struct pmns1__Resultat), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap *soap, int *const*a)
{
	soap_reference(soap, *a, SOAP_TYPE_int);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap *soap, int *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerToint);
	if (soap_out_PointerToint(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap *soap, const char *tag, int id, int *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_int);
	if (id < 0)
		return soap->error;
	return soap_out_int(soap, tag, id, *a, type);
}

SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap *soap, int **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerToint(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap *soap, const char *tag, int **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1))
		return NULL;
	if (!a)
		if (!(a = (int **)soap_malloc(soap, sizeof(int *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_int(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (int **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_int, sizeof(int), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTopmns1__pmConnexionResponse(struct soap *soap, struct pmns1__pmConnexionResponse *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_pmns1__pmConnexionResponse))
		soap_serialize_pmns1__pmConnexionResponse(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTopmns1__pmConnexionResponse(struct soap *soap, struct pmns1__pmConnexionResponse *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerTopmns1__pmConnexionResponse);
	if (soap_out_PointerTopmns1__pmConnexionResponse(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTopmns1__pmConnexionResponse(struct soap *soap, const char *tag, int id, struct pmns1__pmConnexionResponse *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_pmns1__pmConnexionResponse);
	if (id < 0)
		return soap->error;
	return soap_out_pmns1__pmConnexionResponse(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct pmns1__pmConnexionResponse ** SOAP_FMAC4 soap_get_PointerTopmns1__pmConnexionResponse(struct soap *soap, struct pmns1__pmConnexionResponse **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTopmns1__pmConnexionResponse(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__pmConnexionResponse ** SOAP_FMAC4 soap_in_PointerTopmns1__pmConnexionResponse(struct soap *soap, const char *tag, struct pmns1__pmConnexionResponse **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1))
		return NULL;
	if (!a)
		if (!(a = (struct pmns1__pmConnexionResponse **)soap_malloc(soap, sizeof(struct pmns1__pmConnexionResponse *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_pmns1__pmConnexionResponse(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct pmns1__pmConnexionResponse **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_pmns1__pmConnexionResponse, sizeof(struct pmns1__pmConnexionResponse), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTopmns1__Ligne(struct soap *soap, struct pmns1__Ligne *const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_pmns1__Ligne))
		soap_serialize_pmns1__Ligne(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTopmns1__Ligne(struct soap *soap, struct pmns1__Ligne *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerTopmns1__Ligne);
	if (soap_out_PointerTopmns1__Ligne(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTopmns1__Ligne(struct soap *soap, const char *tag, int id, struct pmns1__Ligne *const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_pmns1__Ligne);
	if (id < 0)
		return soap->error;
	return soap_out_pmns1__Ligne(soap, tag, id, *a, type);
}

SOAP_FMAC3 struct pmns1__Ligne ** SOAP_FMAC4 soap_get_PointerTopmns1__Ligne(struct soap *soap, struct pmns1__Ligne **p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTopmns1__Ligne(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 struct pmns1__Ligne ** SOAP_FMAC4 soap_in_PointerTopmns1__Ligne(struct soap *soap, const char *tag, struct pmns1__Ligne **a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1))
		return NULL;
	if (!a)
		if (!(a = (struct pmns1__Ligne **)soap_malloc(soap, sizeof(struct pmns1__Ligne *))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_pmns1__Ligne(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (struct pmns1__Ligne **)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_pmns1__Ligne, sizeof(struct pmns1__Ligne), 0);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap *soap, char **const*a)
{
	if (!soap_reference(soap, *a, SOAP_TYPE_string))
		soap_serialize_string(soap, *a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap *soap, char **const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_PointerTostring);
	if (soap_out_PointerTostring(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap *soap, const char *tag, int id, char **const*a, const char *type)
{
	id = soap_element_id(soap, tag, id, *a, NULL, 0, type, SOAP_TYPE_string);
	if (id < 0)
		return soap->error;
	return soap_out_string(soap, tag, id, *a, type);
}

SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap *soap, char ***p, const char *tag, const char *type)
{
	if ((p = soap_in_PointerTostring(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap *soap, const char *tag, char ***a, const char *type)
{
	if (soap_element_begin_in(soap, tag, 1))
		return NULL;
	if (!a)
		if (!(a = (char ***)soap_malloc(soap, sizeof(char **))))
			return NULL;
	*a = NULL;
	if (!soap->null && *soap->href != '#')
	{	soap_revert(soap);
		if (!(*a = soap_in_string(soap, tag, *a, type)))
			return NULL;
	}
	else
	{	a = (char ***)soap_id_lookup(soap, soap->href, (void**)a, SOAP_TYPE_string, sizeof(char *), 1);
		if (soap->body && soap_element_end_in(soap, tag))
			return NULL;
	}
	return a;
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap *soap, char **a)
{	soap_default_string(soap, a);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap *soap, char *const*a)
{	soap_serialize_string(soap, a);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap *soap, char *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE__QName);
	if (soap_out__QName(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap *soap, const char *tag, int id, char *const*a, const char *type)
{
	return soap_outstring(soap, tag, id, a, type, SOAP_TYPE__QName);
}

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap *soap, char **p, const char *tag, const char *type)
{
	if ((p = soap_in__QName(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap *soap, const char *tag, char **a, const char *type)
{
	return soap_instring(soap, tag, a, type, SOAP_TYPE__QName, 2, -1, -1);
}

SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap *soap, char **a)
{	(void)soap; /* appease -Wall -Werror */
#ifdef SOAP_DEFAULT_string
	*a = SOAP_DEFAULT_string;
#else
	*a = (char *)0;
#endif
}

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap *soap, char *const*a)
{
	soap_reference(soap, *a, SOAP_TYPE_string);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap *soap, char *const*a, const char *tag, const char *type)
{
	register int id = soap_embed(soap, (void*)a, NULL, 0, tag, SOAP_TYPE_string);
	if (soap_out_string(soap, tag, id, a, type))
		return soap->error;
	return soap_putindependent(soap);
}

SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap *soap, const char *tag, int id, char *const*a, const char *type)
{
	return soap_outstring(soap, tag, id, a, type, SOAP_TYPE_string);
}

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap *soap, char **p, const char *tag, const char *type)
{
	if ((p = soap_in_string(soap, tag, p, type)))
		soap_getindependent(soap);
	return p;
}

SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap *soap, const char *tag, char **a, const char *type)
{
	return soap_instring(soap, tag, a, type, SOAP_TYPE_string, 1, -1, -1);
}

#ifdef __cplusplus
}
#endif

/* End of pmC.c */
