/* pmClient.c
   Generated by gSOAP 2.7.6e from pygmalion.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "pmH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) pmClient.c ver 2.7.6e 2006-08-22 07:43:14 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_pmns1__pmConnexion(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *password, char *database, struct pmns1__pmConnexionResponse *_param_1)
{	struct pmns1__pmConnexion soap_tmp_pmns1__pmConnexion;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost";
	if (!soap_action)
		soap_action = "urn:PygmalionAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_pmns1__pmConnexion.login = login;
	soap_tmp_pmns1__pmConnexion.password = password;
	soap_tmp_pmns1__pmConnexion.database = database;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_pmns1__pmConnexion(soap, &soap_tmp_pmns1__pmConnexion);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_pmns1__pmConnexion(soap, &soap_tmp_pmns1__pmConnexion, "pmns1:pmConnexion", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_pmns1__pmConnexion(soap, &soap_tmp_pmns1__pmConnexion, "pmns1:pmConnexion", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_pmns1__pmConnexionResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_pmns1__pmConnexionResponse(soap, _param_1, "pmns1:pmConnexionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_pmns1__pmDeconnexion(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, int *resultat)
{	struct pmns1__pmDeconnexion soap_tmp_pmns1__pmDeconnexion;
	struct pmns1__pmDeconnexionResponse *soap_tmp_pmns1__pmDeconnexionResponse;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost";
	if (!soap_action)
		soap_action = "urn:PygmalionAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_pmns1__pmDeconnexion.id = id;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_pmns1__pmDeconnexion(soap, &soap_tmp_pmns1__pmDeconnexion);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_pmns1__pmDeconnexion(soap, &soap_tmp_pmns1__pmDeconnexion, "pmns1:pmDeconnexion", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_pmns1__pmDeconnexion(soap, &soap_tmp_pmns1__pmDeconnexion, "pmns1:pmDeconnexion", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_int(soap, resultat);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_pmns1__pmDeconnexionResponse = soap_get_pmns1__pmDeconnexionResponse(soap, NULL, "pmns1:pmDeconnexionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (resultat && soap_tmp_pmns1__pmDeconnexionResponse->resultat)
		*resultat = *soap_tmp_pmns1__pmDeconnexionResponse->resultat;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_pmns1__pmSelect(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *query, struct pmns1__pmSelectResponse *_param_2)
{	struct pmns1__pmSelect soap_tmp_pmns1__pmSelect;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost";
	if (!soap_action)
		soap_action = "urn:PygmalionAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_pmns1__pmSelect.id = id;
	soap_tmp_pmns1__pmSelect.query = query;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_pmns1__pmSelect(soap, &soap_tmp_pmns1__pmSelect);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_pmns1__pmSelect(soap, &soap_tmp_pmns1__pmSelect, "pmns1:pmSelect", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_pmns1__pmSelect(soap, &soap_tmp_pmns1__pmSelect, "pmns1:pmSelect", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_pmns1__pmSelectResponse(soap, _param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_pmns1__pmSelectResponse(soap, _param_2, "pmns1:pmSelectResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_pmns1__pmUpdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *query, int *resultat)
{	struct pmns1__pmUpdate soap_tmp_pmns1__pmUpdate;
	struct pmns1__pmUpdateResponse *soap_tmp_pmns1__pmUpdateResponse;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost";
	if (!soap_action)
		soap_action = "urn:PygmalionAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_pmns1__pmUpdate.id = id;
	soap_tmp_pmns1__pmUpdate.query = query;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_pmns1__pmUpdate(soap, &soap_tmp_pmns1__pmUpdate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_pmns1__pmUpdate(soap, &soap_tmp_pmns1__pmUpdate, "pmns1:pmUpdate", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_pmns1__pmUpdate(soap, &soap_tmp_pmns1__pmUpdate, "pmns1:pmUpdate", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_int(soap, resultat);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_pmns1__pmUpdateResponse = soap_get_pmns1__pmUpdateResponse(soap, NULL, "pmns1:pmUpdateResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (resultat && soap_tmp_pmns1__pmUpdateResponse->resultat)
		*resultat = *soap_tmp_pmns1__pmUpdateResponse->resultat;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_pmns1__pmCalcul(struct soap *soap, const char *soap_endpoint, const char *soap_action, double taux, int nb, double *return_)
{	struct pmns1__pmCalcul soap_tmp_pmns1__pmCalcul;
	struct pmns1__pmCalculResponse *soap_tmp_pmns1__pmCalculResponse;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost";
	if (!soap_action)
		soap_action = "urn:PygmalionAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_pmns1__pmCalcul.taux = taux;
	soap_tmp_pmns1__pmCalcul.nb = nb;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_pmns1__pmCalcul(soap, &soap_tmp_pmns1__pmCalcul);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_pmns1__pmCalcul(soap, &soap_tmp_pmns1__pmCalcul, "pmns1:pmCalcul", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_pmns1__pmCalcul(soap, &soap_tmp_pmns1__pmCalcul, "pmns1:pmCalcul", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_double(soap, return_);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_pmns1__pmCalculResponse = soap_get_pmns1__pmCalculResponse(soap, NULL, "pmns1:pmCalculResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (return_ && soap_tmp_pmns1__pmCalculResponse->return_)
		*return_ = *soap_tmp_pmns1__pmCalculResponse->return_;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of pmClient.c */
