/* pmH.h
   Generated by gSOAP 2.7.6e from pygmalion.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef pmH_H
#define pmH_H
#include "pmStub.h"
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
#endif

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_pmns1__Identifiant
#define SOAP_TYPE_pmns1__Identifiant (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__Identifiant(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__Identifiant(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__Identifiant(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_pmns1__Identifiant(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_pmns1__Identifiant(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_pmns1__pmCalcul
#define SOAP_TYPE_pmns1__pmCalcul (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmCalcul(struct soap*, const struct pmns1__pmCalcul *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmCalcul(struct soap*, struct pmns1__pmCalcul *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmCalcul(struct soap*, const struct pmns1__pmCalcul *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmCalcul(struct soap*, const char*, int, const struct pmns1__pmCalcul *, const char*);
SOAP_FMAC3 struct pmns1__pmCalcul * SOAP_FMAC4 soap_get_pmns1__pmCalcul(struct soap*, struct pmns1__pmCalcul *, const char*, const char*);
SOAP_FMAC3 struct pmns1__pmCalcul * SOAP_FMAC4 soap_in_pmns1__pmCalcul(struct soap*, const char*, struct pmns1__pmCalcul *, const char*);

#ifndef SOAP_TYPE_pmns1__pmCalculResponse
#define SOAP_TYPE_pmns1__pmCalculResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmCalculResponse(struct soap*, const struct pmns1__pmCalculResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmCalculResponse(struct soap*, struct pmns1__pmCalculResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmCalculResponse(struct soap*, const struct pmns1__pmCalculResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmCalculResponse(struct soap*, const char*, int, const struct pmns1__pmCalculResponse *, const char*);
SOAP_FMAC3 struct pmns1__pmCalculResponse * SOAP_FMAC4 soap_get_pmns1__pmCalculResponse(struct soap*, struct pmns1__pmCalculResponse *, const char*, const char*);
SOAP_FMAC3 struct pmns1__pmCalculResponse * SOAP_FMAC4 soap_in_pmns1__pmCalculResponse(struct soap*, const char*, struct pmns1__pmCalculResponse *, const char*);

#ifndef SOAP_TYPE_pmns1__pmUpdate
#define SOAP_TYPE_pmns1__pmUpdate (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmUpdate(struct soap*, const struct pmns1__pmUpdate *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmUpdate(struct soap*, struct pmns1__pmUpdate *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmUpdate(struct soap*, const struct pmns1__pmUpdate *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmUpdate(struct soap*, const char*, int, const struct pmns1__pmUpdate *, const char*);
SOAP_FMAC3 struct pmns1__pmUpdate * SOAP_FMAC4 soap_get_pmns1__pmUpdate(struct soap*, struct pmns1__pmUpdate *, const char*, const char*);
SOAP_FMAC3 struct pmns1__pmUpdate * SOAP_FMAC4 soap_in_pmns1__pmUpdate(struct soap*, const char*, struct pmns1__pmUpdate *, const char*);

#ifndef SOAP_TYPE_pmns1__pmUpdateResponse
#define SOAP_TYPE_pmns1__pmUpdateResponse (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmUpdateResponse(struct soap*, const struct pmns1__pmUpdateResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmUpdateResponse(struct soap*, struct pmns1__pmUpdateResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmUpdateResponse(struct soap*, const struct pmns1__pmUpdateResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmUpdateResponse(struct soap*, const char*, int, const struct pmns1__pmUpdateResponse *, const char*);
SOAP_FMAC3 struct pmns1__pmUpdateResponse * SOAP_FMAC4 soap_get_pmns1__pmUpdateResponse(struct soap*, struct pmns1__pmUpdateResponse *, const char*, const char*);
SOAP_FMAC3 struct pmns1__pmUpdateResponse * SOAP_FMAC4 soap_in_pmns1__pmUpdateResponse(struct soap*, const char*, struct pmns1__pmUpdateResponse *, const char*);

#ifndef SOAP_TYPE_pmns1__pmSelect
#define SOAP_TYPE_pmns1__pmSelect (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmSelect(struct soap*, const struct pmns1__pmSelect *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmSelect(struct soap*, struct pmns1__pmSelect *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmSelect(struct soap*, const struct pmns1__pmSelect *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmSelect(struct soap*, const char*, int, const struct pmns1__pmSelect *, const char*);
SOAP_FMAC3 struct pmns1__pmSelect * SOAP_FMAC4 soap_get_pmns1__pmSelect(struct soap*, struct pmns1__pmSelect *, const char*, const char*);
SOAP_FMAC3 struct pmns1__pmSelect * SOAP_FMAC4 soap_in_pmns1__pmSelect(struct soap*, const char*, struct pmns1__pmSelect *, const char*);

#ifndef SOAP_TYPE_pmns1__pmSelectResponse
#define SOAP_TYPE_pmns1__pmSelectResponse (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmSelectResponse(struct soap*, const struct pmns1__pmSelectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmSelectResponse(struct soap*, struct pmns1__pmSelectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmSelectResponse(struct soap*, const struct pmns1__pmSelectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmSelectResponse(struct soap*, const char*, int, const struct pmns1__pmSelectResponse *, const char*);
SOAP_FMAC3 struct pmns1__pmSelectResponse * SOAP_FMAC4 soap_get_pmns1__pmSelectResponse(struct soap*, struct pmns1__pmSelectResponse *, const char*, const char*);
SOAP_FMAC3 struct pmns1__pmSelectResponse * SOAP_FMAC4 soap_in_pmns1__pmSelectResponse(struct soap*, const char*, struct pmns1__pmSelectResponse *, const char*);

#ifndef SOAP_TYPE_pmns1__pmDeconnexion
#define SOAP_TYPE_pmns1__pmDeconnexion (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmDeconnexion(struct soap*, const struct pmns1__pmDeconnexion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmDeconnexion(struct soap*, struct pmns1__pmDeconnexion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmDeconnexion(struct soap*, const struct pmns1__pmDeconnexion *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmDeconnexion(struct soap*, const char*, int, const struct pmns1__pmDeconnexion *, const char*);
SOAP_FMAC3 struct pmns1__pmDeconnexion * SOAP_FMAC4 soap_get_pmns1__pmDeconnexion(struct soap*, struct pmns1__pmDeconnexion *, const char*, const char*);
SOAP_FMAC3 struct pmns1__pmDeconnexion * SOAP_FMAC4 soap_in_pmns1__pmDeconnexion(struct soap*, const char*, struct pmns1__pmDeconnexion *, const char*);

#ifndef SOAP_TYPE_pmns1__pmDeconnexionResponse
#define SOAP_TYPE_pmns1__pmDeconnexionResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmDeconnexionResponse(struct soap*, const struct pmns1__pmDeconnexionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmDeconnexionResponse(struct soap*, struct pmns1__pmDeconnexionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmDeconnexionResponse(struct soap*, const struct pmns1__pmDeconnexionResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmDeconnexionResponse(struct soap*, const char*, int, const struct pmns1__pmDeconnexionResponse *, const char*);
SOAP_FMAC3 struct pmns1__pmDeconnexionResponse * SOAP_FMAC4 soap_get_pmns1__pmDeconnexionResponse(struct soap*, struct pmns1__pmDeconnexionResponse *, const char*, const char*);
SOAP_FMAC3 struct pmns1__pmDeconnexionResponse * SOAP_FMAC4 soap_in_pmns1__pmDeconnexionResponse(struct soap*, const char*, struct pmns1__pmDeconnexionResponse *, const char*);

#ifndef SOAP_TYPE_pmns1__pmConnexion
#define SOAP_TYPE_pmns1__pmConnexion (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmConnexion(struct soap*, const struct pmns1__pmConnexion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmConnexion(struct soap*, struct pmns1__pmConnexion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmConnexion(struct soap*, const struct pmns1__pmConnexion *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmConnexion(struct soap*, const char*, int, const struct pmns1__pmConnexion *, const char*);
SOAP_FMAC3 struct pmns1__pmConnexion * SOAP_FMAC4 soap_get_pmns1__pmConnexion(struct soap*, struct pmns1__pmConnexion *, const char*, const char*);
SOAP_FMAC3 struct pmns1__pmConnexion * SOAP_FMAC4 soap_in_pmns1__pmConnexion(struct soap*, const char*, struct pmns1__pmConnexion *, const char*);

#ifndef SOAP_TYPE_pmns1__pmConnexionResponse
#define SOAP_TYPE_pmns1__pmConnexionResponse (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__pmConnexionResponse(struct soap*, const struct pmns1__pmConnexionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__pmConnexionResponse(struct soap*, struct pmns1__pmConnexionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__pmConnexionResponse(struct soap*, const struct pmns1__pmConnexionResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__pmConnexionResponse(struct soap*, const char*, int, const struct pmns1__pmConnexionResponse *, const char*);
SOAP_FMAC3 struct pmns1__pmConnexionResponse * SOAP_FMAC4 soap_get_pmns1__pmConnexionResponse(struct soap*, struct pmns1__pmConnexionResponse *, const char*, const char*);
SOAP_FMAC3 struct pmns1__pmConnexionResponse * SOAP_FMAC4 soap_in_pmns1__pmConnexionResponse(struct soap*, const char*, struct pmns1__pmConnexionResponse *, const char*);

#ifndef SOAP_TYPE_pmns1__Resultat
#define SOAP_TYPE_pmns1__Resultat (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__Resultat(struct soap*, const struct pmns1__Resultat *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__Resultat(struct soap*, struct pmns1__Resultat *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__Resultat(struct soap*, const struct pmns1__Resultat *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__Resultat(struct soap*, const char*, int, const struct pmns1__Resultat *, const char*);
SOAP_FMAC3 struct pmns1__Resultat * SOAP_FMAC4 soap_get_pmns1__Resultat(struct soap*, struct pmns1__Resultat *, const char*, const char*);
SOAP_FMAC3 struct pmns1__Resultat * SOAP_FMAC4 soap_in_pmns1__Resultat(struct soap*, const char*, struct pmns1__Resultat *, const char*);

#ifndef SOAP_TYPE_pmns1__Ligne
#define SOAP_TYPE_pmns1__Ligne (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_pmns1__Ligne(struct soap*, const struct pmns1__Ligne *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_pmns1__Ligne(struct soap*, struct pmns1__Ligne *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_pmns1__Ligne(struct soap*, const struct pmns1__Ligne *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_pmns1__Ligne(struct soap*, const char*, int, const struct pmns1__Ligne *, const char*);
SOAP_FMAC3 struct pmns1__Ligne * SOAP_FMAC4 soap_get_pmns1__Ligne(struct soap*, struct pmns1__Ligne *, const char*, const char*);
SOAP_FMAC3 struct pmns1__Ligne * SOAP_FMAC4 soap_in_pmns1__Ligne(struct soap*, const char*, struct pmns1__Ligne *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTodouble
#define SOAP_TYPE_PointerTodouble (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTodouble(struct soap*, double *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTodouble(struct soap*, double *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTodouble(struct soap*, const char *, int, double *const*, const char *);
SOAP_FMAC3 double ** SOAP_FMAC4 soap_get_PointerTodouble(struct soap*, double **, const char*, const char*);
SOAP_FMAC3 double ** SOAP_FMAC4 soap_in_PointerTodouble(struct soap*, const char*, double **, const char*);

#ifndef SOAP_TYPE_PointerTopmns1__pmSelectResponse
#define SOAP_TYPE_PointerTopmns1__pmSelectResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTopmns1__pmSelectResponse(struct soap*, struct pmns1__pmSelectResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTopmns1__pmSelectResponse(struct soap*, struct pmns1__pmSelectResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTopmns1__pmSelectResponse(struct soap*, const char *, int, struct pmns1__pmSelectResponse *const*, const char *);
SOAP_FMAC3 struct pmns1__pmSelectResponse ** SOAP_FMAC4 soap_get_PointerTopmns1__pmSelectResponse(struct soap*, struct pmns1__pmSelectResponse **, const char*, const char*);
SOAP_FMAC3 struct pmns1__pmSelectResponse ** SOAP_FMAC4 soap_in_PointerTopmns1__pmSelectResponse(struct soap*, const char*, struct pmns1__pmSelectResponse **, const char*);

#ifndef SOAP_TYPE_PointerTopmns1__Resultat
#define SOAP_TYPE_PointerTopmns1__Resultat (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTopmns1__Resultat(struct soap*, struct pmns1__Resultat *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTopmns1__Resultat(struct soap*, struct pmns1__Resultat *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTopmns1__Resultat(struct soap*, const char *, int, struct pmns1__Resultat *const*, const char *);
SOAP_FMAC3 struct pmns1__Resultat ** SOAP_FMAC4 soap_get_PointerTopmns1__Resultat(struct soap*, struct pmns1__Resultat **, const char*, const char*);
SOAP_FMAC3 struct pmns1__Resultat ** SOAP_FMAC4 soap_in_PointerTopmns1__Resultat(struct soap*, const char*, struct pmns1__Resultat **, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE_PointerTopmns1__pmConnexionResponse
#define SOAP_TYPE_PointerTopmns1__pmConnexionResponse (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTopmns1__pmConnexionResponse(struct soap*, struct pmns1__pmConnexionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTopmns1__pmConnexionResponse(struct soap*, struct pmns1__pmConnexionResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTopmns1__pmConnexionResponse(struct soap*, const char *, int, struct pmns1__pmConnexionResponse *const*, const char *);
SOAP_FMAC3 struct pmns1__pmConnexionResponse ** SOAP_FMAC4 soap_get_PointerTopmns1__pmConnexionResponse(struct soap*, struct pmns1__pmConnexionResponse **, const char*, const char*);
SOAP_FMAC3 struct pmns1__pmConnexionResponse ** SOAP_FMAC4 soap_in_PointerTopmns1__pmConnexionResponse(struct soap*, const char*, struct pmns1__pmConnexionResponse **, const char*);

#ifndef SOAP_TYPE_PointerTopmns1__Ligne
#define SOAP_TYPE_PointerTopmns1__Ligne (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTopmns1__Ligne(struct soap*, struct pmns1__Ligne *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTopmns1__Ligne(struct soap*, struct pmns1__Ligne *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTopmns1__Ligne(struct soap*, const char *, int, struct pmns1__Ligne *const*, const char *);
SOAP_FMAC3 struct pmns1__Ligne ** SOAP_FMAC4 soap_get_PointerTopmns1__Ligne(struct soap*, struct pmns1__Ligne **, const char*, const char*);
SOAP_FMAC3 struct pmns1__Ligne ** SOAP_FMAC4 soap_in_PointerTopmns1__Ligne(struct soap*, const char*, struct pmns1__Ligne **, const char*);

#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of pmH.h */
