/* pmStub.h
   Generated by gSOAP 2.7.6e from pygmalion.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef pmStub_H
#define pmStub_H
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_pmns1__Ligne
#define SOAP_TYPE_pmns1__Ligne (7)
/* pmns1:Ligne */
struct pmns1__Ligne
{
	int __sizevaleurs;	/* sequence of elements <valeurs> */
	char **valeurs;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_pmns1__Resultat
#define SOAP_TYPE_pmns1__Resultat (9)
/* pmns1:Resultat */
struct pmns1__Resultat
{
	int __sizelignes;	/* sequence of elements <lignes> */
	struct pmns1__Ligne *lignes;	/* required element of type pmns1:Ligne */
};
#endif

#ifndef SOAP_TYPE_pmns1__pmConnexionResponse
#define SOAP_TYPE_pmns1__pmConnexionResponse (11)
/* pmns1:pmConnexionResponse */
struct pmns1__pmConnexionResponse
{
	int id;	/* RPC return element */	/* required element of type pmns1:Identifiant */
};
#endif

#ifndef SOAP_TYPE_pmns1__pmConnexion
#define SOAP_TYPE_pmns1__pmConnexion (14)
/* pmns1:pmConnexion */
struct pmns1__pmConnexion
{
	char *login;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *database;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_pmns1__pmDeconnexionResponse
#define SOAP_TYPE_pmns1__pmDeconnexionResponse (17)
/* pmns1:pmDeconnexionResponse */
struct pmns1__pmDeconnexionResponse
{
	int *resultat;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_pmns1__pmDeconnexion
#define SOAP_TYPE_pmns1__pmDeconnexion (18)
/* pmns1:pmDeconnexion */
struct pmns1__pmDeconnexion
{
	int id;	/* required element of type pmns1:Identifiant */
};
#endif

#ifndef SOAP_TYPE_pmns1__pmSelectResponse
#define SOAP_TYPE_pmns1__pmSelectResponse (19)
/* pmns1:pmSelectResponse */
struct pmns1__pmSelectResponse
{
	struct pmns1__Resultat *resultat;	/* RPC return element */	/* optional element of type pmns1:Resultat */
};
#endif

#ifndef SOAP_TYPE_pmns1__pmSelect
#define SOAP_TYPE_pmns1__pmSelect (23)
/* pmns1:pmSelect */
struct pmns1__pmSelect
{
	int id;	/* required element of type pmns1:Identifiant */
	char *query;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_pmns1__pmUpdateResponse
#define SOAP_TYPE_pmns1__pmUpdateResponse (25)
/* pmns1:pmUpdateResponse */
struct pmns1__pmUpdateResponse
{
	int *resultat;	/* RPC return element */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_pmns1__pmUpdate
#define SOAP_TYPE_pmns1__pmUpdate (26)
/* pmns1:pmUpdate */
struct pmns1__pmUpdate
{
	int id;	/* required element of type pmns1:Identifiant */
	char *query;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_pmns1__pmCalculResponse
#define SOAP_TYPE_pmns1__pmCalculResponse (30)
/* pmns1:pmCalculResponse */
struct pmns1__pmCalculResponse
{
	double *return_;	/* RPC return element */	/* optional element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE_pmns1__pmCalcul
#define SOAP_TYPE_pmns1__pmCalcul (31)
/* pmns1:pmCalcul */
struct pmns1__pmCalcul
{
	double taux;	/* required element of type xsd:double */
	int nb;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (34)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	void *dummy;	/* transient */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (35)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (37)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (38)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (39)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (4)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE_pmns1__Identifiant
#define SOAP_TYPE_pmns1__Identifiant (6)
typedef int pmns1__Identifiant;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operations                                                         *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 pmns1__pmConnexion(struct soap*, char *login, char *password, char *database, struct pmns1__pmConnexionResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 pmns1__pmDeconnexion(struct soap*, int id, int *resultat);

SOAP_FMAC5 int SOAP_FMAC6 pmns1__pmSelect(struct soap*, int id, char *query, struct pmns1__pmSelectResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 pmns1__pmUpdate(struct soap*, int id, char *query, int *resultat);

SOAP_FMAC5 int SOAP_FMAC6 pmns1__pmCalcul(struct soap*, double taux, int nb, double *return_);

/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_pmns1__pmConnexion(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *password, char *database, struct pmns1__pmConnexionResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_pmns1__pmDeconnexion(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, int *resultat);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_pmns1__pmSelect(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *query, struct pmns1__pmSelectResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_pmns1__pmUpdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, int id, char *query, int *resultat);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_pmns1__pmCalcul(struct soap *soap, const char *soap_endpoint, const char *soap_action, double taux, int nb, double *return_);

/******************************************************************************\
 *                                                                            *
 * Skeletons                                                                  *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_pmns1__pmConnexion(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_pmns1__pmDeconnexion(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_pmns1__pmSelect(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_pmns1__pmUpdate(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_pmns1__pmCalcul(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of pmStub.h */
