/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* Generated by Pygmalion */
#ifndef __mozC01step_h__
#define __mozC01step_h__

#include "mozIC01step.h"
#include "nsServiceManagerUtils.h"
#include "nsCOMPtr.h"
#include "nsString.h"


class mozC01step : public mozIC01step
{
 public:
  NS_DECL_ISUPPORTS
  NS_DECL_MOZIC01STEP

  mozC01step();

 private:
  ~mozC01step();

 protected:
  nsString mMasterIndex;
  PRUint32 mIndex;
  nsString mDetailKey;
};

#endif

/* Generated by Pygmalion */

