/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* Generated by Pygmalion */

#include "mozC02gestsea.h"

/* No SOAP Encoding code */

NS_IMPL_ISUPPORTS1(mozC02gestsea, mozIC02gestsea)

mozC02gestsea::mozC02gestsea()
{
}

mozC02gestsea::~mozC02gestsea()
{
}


/* Generated by Pygmalion */

