/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* Generated by Pygmalion */
#ifndef __mozC00gestsea_h__
#define __mozC00gestsea_h__

#include "mozIC00gestsea.h"
#include "nsServiceManagerUtils.h"
#include "nsCOMPtr.h"
#include "nsISOAPParameter.h"
#include "nsString.h"
#include "nsMemory.h"
#include "nsIVariant.h"
#include "nsISOAPBlock.h"
#include "nsISOAPMessage.h"
#include "nsISOAPCall.h"
#include "nsISOAPEncoding.h"
#include "nsISOAPResponse.h"
#include "nsISOAPFault.h"
#include "nsIDOMElement.h"
#include "nsIDOMNode.h"
#include "nsIDOMDocument.h"
#include "nsIDOMSerializer.h"
#include "nsEmbedCID.h"
#include "nsNetCID.h"
#include "nsIPromptService.h"


class mozC00gestsea : public mozIC00gestsea
{
 public:
  NS_DECL_ISUPPORTS
  NS_DECL_MOZIC00GESTSEA

  mozC00gestsea();

 private:
  ~mozC00gestsea();

 protected:
  nsString mTransportURI;
};

#endif

/* Generated by Pygmalion */

