/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* Generated by Pygmalion */

#include "mozC00gestsea.h"

/* No SOAP Encoding code */

NS_IMPL_ISUPPORTS1(mozC00gestsea, mozIC00gestsea)

mozC00gestsea::mozC00gestsea()
{
}

mozC00gestsea::~mozC00gestsea()
{
}


/* Generated by Pygmalion */

