/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* Generated by Pygmalion */

#include "mozC01step.h"

/* No SOAP Encoding code */

NS_IMPL_ISUPPORTS1(mozC01step, mozIC01step)

mozC01step::mozC01step()
{
}

mozC01step::~mozC01step()
{
}


/* Generated by Pygmalion */

