#include "nsISupports.idl"
#include "mozIC01step.idl"
#include "nsITreeBoxObject.idl"
#include "nsIDOMMouseEvent.idl"
#include "nsIDOMKeyEvent.idl"
#include "nsIDOMWindowInternal.idl"
#include "nsIDOMXULElement.idl"
#include "nsIVariant.idl"
[scriptable, uuid(8b1506a2-a137-4c2f-93a7-0ec16d76e3a9)]
interface mozIC02gestsea : nsISupports
{
  AString getStringPref(in string pref);
  void menuMenuGestseaDisplay();
  void menuMenuGseaPrincipalDisplay();
  void treeI0017dSet(in nsITreeBoxObject tree);
  void treeI0017dOnClick(in nsIDOMMouseEvent event);
  void detailListI0016dSelect();
  void detailListI001DdInsert();
  void treeI001FdSet(in nsITreeBoxObject tree);
  void treeI001FdOnClick(in nsIDOMMouseEvent event);
  void detailListI001DdSelect();
  void treeI002AdSet(in nsITreeBoxObject tree);
  void treeI002AdOnClick(in nsIDOMMouseEvent event);
  void detailListI0029dSelect();
  void treeI0030dSet(in nsITreeBoxObject tree);
  void treeI0030dOnClick(in nsIDOMMouseEvent event);
  void detailListI002FdSelect();
  void detailBasePartenaireContactSelect(in AString key);
  void menulistI003CdRefresh(in nsIDOMKeyEvent event);
  void menulistI003EdRefresh(in nsIDOMKeyEvent event);
  void menulistI0045dRefresh(in nsIDOMKeyEvent event);
  void detailBasePartenaireContactUpdate(in AString key);
  void detailBasePartenaireContactUpdateAccept();
  void menulistI004DdRefresh(in nsIDOMKeyEvent event);
  void menulistI004FdRefresh(in nsIDOMKeyEvent event);
  void menulistI0056dRefresh(in nsIDOMKeyEvent event);
  void detailBasePartenaireContactInsert();
  void detailBasePartenaireContactInsertAccept();
  void detailBasePartenaireContactDelete(in AString key, in boolean confirmBeforeDelete);
  void detailBasePartenaireContactCancel();
  void detailBasePartenaireObservationSelect(in AString key);
  void menulistI0063dRefresh(in nsIDOMKeyEvent event);
  void menulistI0065dRefresh(in nsIDOMKeyEvent event);
  void detailBasePartenaireObservationUpdate(in AString key);
  void detailBasePartenaireObservationUpdateAccept();
  void menulistI0069dRefresh(in nsIDOMKeyEvent event);
  void menulistI006BdRefresh(in nsIDOMKeyEvent event);
  void detailBasePartenaireObservationInsert();
  void detailBasePartenaireObservationInsertAccept();
  void detailBasePartenaireObservationDelete(in AString key, in boolean confirmBeforeDelete);
  void detailBasePartenaireObservationCancel();
  void detailBasePartenaireAttributSelect(in AString key);
  void menulistI0079dRefresh(in nsIDOMKeyEvent event);
  void menulistI007BdRefresh(in nsIDOMKeyEvent event);
  void menulistI007DdRefresh(in nsIDOMKeyEvent event);
  void detailBasePartenaireAttributUpdate(in AString key);
  void detailBasePartenaireAttributUpdateAccept();
  void menulistI0081dRefresh(in nsIDOMKeyEvent event);
  void menulistI0083dRefresh(in nsIDOMKeyEvent event);
  void menulistI0085dRefresh(in nsIDOMKeyEvent event);
  void detailBasePartenaireAttributInsert();
  void detailBasePartenaireAttributInsertAccept();
  void detailBasePartenaireAttributDelete(in AString key, in boolean confirmBeforeDelete);
  void detailBasePartenaireAttributCancel();
  void detailListI00C9dInsert();
  void treeI00CBdSet(in nsITreeBoxObject tree);
  void treeI00CBdOnClick(in nsIDOMMouseEvent event);
  void detailListI00C9dSelect();
  void treeI00D4dSet(in nsITreeBoxObject tree);
  void treeI00D4dOnClick(in nsIDOMMouseEvent event);
  void detailListI00D3dSelect();
  void treeI00DBdSet(in nsITreeBoxObject tree);
  void treeI00DBdOnClick(in nsIDOMMouseEvent event);
  void detailListI00DAdSelect();
  void treeI00E2dSet(in nsITreeBoxObject tree);
  void treeI00E2dOnClick(in nsIDOMMouseEvent event);
  void detailListI00E1dSelect();
  void treeI00E6dSet(in nsITreeBoxObject tree);
  void treeI00E6dOnClick(in nsIDOMMouseEvent event);
  void detailListI00E5dSelect();
  void detailGestionVentesCommandeSelect(in AString key);
  void menulistI00EBdRefresh(in nsIDOMKeyEvent event);
  void menulistI00F0dRefresh(in nsIDOMKeyEvent event);
  void menulistI00F2dRefresh(in nsIDOMKeyEvent event);
  void menulistI00F4dRefresh(in nsIDOMKeyEvent event);
  void menulistI00F6dRefresh(in nsIDOMKeyEvent event);
  void menulistI00F8dRefresh(in nsIDOMKeyEvent event);
  void menulistI00FAdRefresh(in nsIDOMKeyEvent event);
  void detailGestionVentesCommandeUpdate(in AString key);
  void detailGestionVentesCommandeUpdateAccept();
  void menulistI0104dRefresh(in nsIDOMKeyEvent event);
  void menulistI0109dRefresh(in nsIDOMKeyEvent event);
  void menulistI010BdRefresh(in nsIDOMKeyEvent event);
  void menulistI010DdRefresh(in nsIDOMKeyEvent event);
  void menulistI010FdRefresh(in nsIDOMKeyEvent event);
  void menulistI0111dRefresh(in nsIDOMKeyEvent event);
  void menulistI0113dRefresh(in nsIDOMKeyEvent event);
  void detailGestionVentesCommandeInsert();
  void detailGestionVentesCommandeInsertAccept();
  void detailGestionVentesCommandeDelete(in AString key, in boolean confirmBeforeDelete);
  void detailGestionVentesCommandeCancel();
  void treeI011DdSet(in nsITreeBoxObject tree);
  void treeI011DdOnClick(in nsIDOMMouseEvent event);
  void detailGestionVentesCommandeSearch(in AString target);
  void treeI014DdSet(in nsITreeBoxObject tree);
  void treeI014DdOnClick(in nsIDOMMouseEvent event);
  void detailListI014CdSelect();
  void treeI0153dSet(in nsITreeBoxObject tree);
  void treeI0153dOnClick(in nsIDOMMouseEvent event);
  void detailListI0152dSelect();
  void detailGestionVentesCommandeLigneSelect(in AString key);
  void menulistI015AdRefresh(in nsIDOMKeyEvent event);
  void menulistI015CdRefresh(in nsIDOMKeyEvent event);
  void detailGestionVentesCommandeLigneUpdate(in AString key);
  void detailGestionVentesCommandeLigneUpdateAccept();
  void menulistI0164dRefresh(in nsIDOMKeyEvent event);
  void menulistI0166dRefresh(in nsIDOMKeyEvent event);
  void detailGestionVentesCommandeLigneInsert();
  void detailGestionVentesCommandeLigneInsertAccept();
  void detailGestionVentesCommandeLigneDelete(in AString key, in boolean confirmBeforeDelete);
  void detailGestionVentesCommandeLigneCancel();
  void detailListI017FdInsert();
  void treeI0181dSet(in nsITreeBoxObject tree);
  void treeI0181dOnClick(in nsIDOMMouseEvent event);
  void detailListI017FdSelect();
  void detailListI018CdInsert();
  void treeI018EdSet(in nsITreeBoxObject tree);
  void treeI018EdOnClick(in nsIDOMMouseEvent event);
  void detailListI018CdSelect();
  void detailListI0195dInsert();
  void treeI0197dSet(in nsITreeBoxObject tree);
  void treeI0197dOnClick(in nsIDOMMouseEvent event);
  void detailListI0195dSelect();
  void treeI019EdSet(in nsITreeBoxObject tree);
  void treeI019EdOnClick(in nsIDOMMouseEvent event);
  void detailListI019DdSelect();
  void treeI01A3dSet(in nsITreeBoxObject tree);
  void treeI01A3dOnClick(in nsIDOMMouseEvent event);
  void detailListI01A2dSelect();
  void treeI01A7dSet(in nsITreeBoxObject tree);
  void treeI01A7dOnClick(in nsIDOMMouseEvent event);
  void detailListI01A6dSelect();
  void detailListI01ACdInsert();
  void treeI01AEdSet(in nsITreeBoxObject tree);
  void treeI01AEdOnClick(in nsIDOMMouseEvent event);
  void detailListI01ACdSelect();
  void treeI01B7dSet(in nsITreeBoxObject tree);
  void treeI01B7dOnClick(in nsIDOMMouseEvent event);
  void detailListI01B6dSelect();
  void treeI01BCdSet(in nsITreeBoxObject tree);
  void treeI01BCdOnClick(in nsIDOMMouseEvent event);
  void detailListI01BBdSelect();
  void treeI01C1dSet(in nsITreeBoxObject tree);
  void treeI01C1dOnClick(in nsIDOMMouseEvent event);
  void detailListI01C0dSelect();
  void treeI01C8dSet(in nsITreeBoxObject tree);
  void treeI01C8dOnClick(in nsIDOMMouseEvent event);
  void detailListI01C7dSelect();
  void treeI01CEdSet(in nsITreeBoxObject tree);
  void treeI01CEdOnClick(in nsIDOMMouseEvent event);
  void detailListI01CDdSelect();
  void treeI01DAdSet(in nsITreeBoxObject tree);
  void treeI01DAdOnClick(in nsIDOMMouseEvent event);
  void detailListI01D9dSelect();
  void detailBasePartenaireSelect(in AString key);
  void menulistI01E4dRefresh(in nsIDOMKeyEvent event);
  void menulistI01EAdRefresh(in nsIDOMKeyEvent event);
  void menulistI01EDdRefresh(in nsIDOMKeyEvent event);
  void menulistI01EFdRefresh(in nsIDOMKeyEvent event);
  void detailBasePartenaireUpdate(in AString key);
  void detailBasePartenaireUpdateAccept();
  void menulistI01F6dRefresh(in nsIDOMKeyEvent event);
  void menulistI01FCdRefresh(in nsIDOMKeyEvent event);
  void menulistI01FFdRefresh(in nsIDOMKeyEvent event);
  void menulistI0201dRefresh(in nsIDOMKeyEvent event);
  void detailBasePartenaireInsert();
  void detailBasePartenaireInsertAccept();
  void detailBasePartenaireDelete(in AString key, in boolean confirmBeforeDelete);
  void detailBasePartenaireCancel();
  void treeI0208dSet(in nsITreeBoxObject tree);
  void treeI0208dOnClick(in nsIDOMMouseEvent event);
  void detailBasePartenaireSearch(in AString target);
  void displayStep(in mozIC01step step);
  void saveStep(in AString masterIndex, in unsigned long index, in AString detailKey);
  void now();
  void back();
  void forward();
  void home();
  boolean init(in nsIDOMWindowInternal window);
  void quit();
  void initPointers();
  void menulistClear(in nsIDOMXULElement menupopup);
  void setValue(in unsigned long field, in AString value);
  AString getValue(in unsigned long field);
  void executeP0000(in AString p_key);
  void executeP0001(in AString p_key);
  void executeP0002(in AString p_key);
  void executeP0003(in AString p_key);
  void executeP0004(in AString p_key);
  void executeP0005(in AString p_key);
  void executeP0006(in AString p_key);
  void executeP0007(in AString p_key);
  void executeP0008(in ACString p_search);
  void executeP0009(in ACString p_search);
  void executeP000A(in AString p_key);
  void executeP000B(in ACString p_search);
  void executeP000C(in ACString p_search);
  void executeP000D(in AString p_key);
  void executeP000E(in ACString p_search);
  void executeP000F(in ACString p_search);
  void executeP0010(in AString p_key);
  void executeP0011(in AString p_key);
  void executeP0012(in AString p_key, in ACString p_field1, in ACString p_field2, in ACString p_field3, in ACString p_field4, in ACString p_field5, in ACString p_field6, in ACString p_field7, in ACString p_field8, in ACString p_field9, in ACString p_field10, in ACString p_field11, in ACString p_field12, in ACString p_field13);
  void executeP0013(in ACString p_search);
  void executeP0014(in ACString p_search);
  void executeP0015(in AString p_key);
  void executeP0016(in ACString p_search);
  void executeP0017(in ACString p_search);
  void executeP0018(in AString p_key);
  void executeP0019(in ACString p_search);
  void executeP001A(in ACString p_search);
  void executeP001B(in AString p_key);
  void executeP001C(in AString p_key, in ACString p_field1, in ACString p_field2, in ACString p_field3, in ACString p_field4, in ACString p_field5, in ACString p_field6, in ACString p_field7, in ACString p_field8, in ACString p_field9, in ACString p_field10, in ACString p_field11, in ACString p_field12, in ACString p_field13);
  void executeP001D();
  void executeP001E(in AString p_key);
  void executeP001F(in AString p_key);
  void executeP0020(in ACString p_search);
  void executeP0021(in ACString p_search);
  void executeP0022(in AString p_key);
  void executeP0023(in ACString p_search);
  void executeP0024(in ACString p_search);
  void executeP0025(in AString p_key);
  void executeP0026(in AString p_key);
  void executeP0027(in AString p_key, in ACString p_field1, in ACString p_field2, in ACString p_field3);
  void executeP0028(in ACString p_search);
  void executeP0029(in ACString p_search);
  void executeP002A(in AString p_key);
  void executeP002B(in ACString p_search);
  void executeP002C(in ACString p_search);
  void executeP002D(in AString p_key);
  void executeP002E(in AString p_key, in ACString p_field1, in ACString p_field2, in ACString p_field3);
  void executeP002F();
  void executeP0030(in AString p_key);
  void executeP0031(in AString p_key);
  void executeP0032(in AString p_key);
  void executeP0033(in AString p_key);
  void executeP0034(in AString p_key);
  void executeP0035(in ACString p_search);
  void executeP0036(in ACString p_search);
  void executeP0037(in AString p_key);
  void executeP0038(in ACString p_search);
  void executeP0039(in ACString p_search);
  void executeP003A(in AString p_key);
  void executeP003B(in ACString p_search);
  void executeP003C(in ACString p_search);
  void executeP003D(in AString p_key);
  void executeP003E(in AString p_key);
  void executeP003F(in AString p_key, in ACString p_field1, in ACString p_field2, in ACString p_field3, in ACString p_field4);
  void executeP0040(in ACString p_search);
  void executeP0041(in ACString p_search);
  void executeP0042(in AString p_key);
  void executeP0043(in ACString p_search);
  void executeP0044(in ACString p_search);
  void executeP0045(in AString p_key);
  void executeP0046(in ACString p_search);
  void executeP0047(in ACString p_search);
  void executeP0048(in AString p_key);
  void executeP0049(in AString p_key, in ACString p_field1, in ACString p_field2, in ACString p_field3, in ACString p_field4);
  void executeP004A();
  void executeP004B(in AString p_key);
  void executeP004C(in AString p_key);
  void executeP004D(in AString p_key);
  void executeP004E(in AString p_key);
  void executeP004F(in AString p_key);
  void executeP0050(in AString p_key);
  void executeP0051(in AString p_key);
  void executeP0052(in AString p_key);
  void executeP0053(in AString p_key);
  void executeP0054(in AString p_key);
  void executeP0055(in AString p_key);
  void executeP0056(in AString p_key);
  void executeP0057(in AString p_key);
  void executeP0058(in AString p_key);
  void executeP0059(in AString p_key);
  void executeP005A(in AString p_key);
  void executeP005B(in ACString p_search);
  void executeP005C(in ACString p_search);
  void executeP005D(in AString p_key);
  void executeP005E(in ACString p_search);
  void executeP005F(in ACString p_search);
  void executeP0060(in AString p_key);
  void executeP0061(in ACString p_search);
  void executeP0062(in ACString p_search);
  void executeP0063(in AString p_key);
  void executeP0064(in ACString p_search);
  void executeP0065(in ACString p_search);
  void executeP0066(in AString p_key);
  void executeP0067(in ACString p_search);
  void executeP0068(in ACString p_search);
  void executeP0069(in AString p_key);
  void executeP006A(in ACString p_search);
  void executeP006B(in ACString p_search);
  void executeP006C(in AString p_key);
  void executeP006D(in ACString p_search);
  void executeP006E(in ACString p_search);
  void executeP006F(in AString p_key);
  void executeP0070(in AString p_key);
  void executeP0071(in AString p_key, in ACString p_field1, in ACString p_field2, in ACString p_field3, in ACString p_field4, in ACString p_field5, in ACString p_field6, in ACString p_field7, in ACString p_field8, in ACString p_field9, in ACString p_field10, in ACString p_field11, in ACString p_field12, in ACString p_field13, in ACString p_field14, in ACString p_field15, in ACString p_field16, in ACString p_field17);
  void executeP0072(in ACString p_search);
  void executeP0073(in ACString p_search);
  void executeP0074(in AString p_key);
  void executeP0075(in ACString p_search);
  void executeP0076(in ACString p_search);
  void executeP0077(in AString p_key);
  void executeP0078(in ACString p_search);
  void executeP0079(in ACString p_search);
  void executeP007A(in AString p_key);
  void executeP007B(in ACString p_search);
  void executeP007C(in ACString p_search);
  void executeP007D(in AString p_key);
  void executeP007E(in ACString p_search);
  void executeP007F(in ACString p_search);
  void executeP0080(in AString p_key);
  void executeP0081(in ACString p_search);
  void executeP0082(in ACString p_search);
  void executeP0083(in AString p_key);
  void executeP0084(in ACString p_search);
  void executeP0085(in ACString p_search);
  void executeP0086(in AString p_key);
  void executeP0087(in AString p_key, in ACString p_field1, in ACString p_field2, in ACString p_field3, in ACString p_field4, in ACString p_field5, in ACString p_field6, in ACString p_field7, in ACString p_field8, in ACString p_field9, in ACString p_field10, in ACString p_field11, in ACString p_field12, in ACString p_field13, in ACString p_field14, in ACString p_field15, in ACString p_field16, in ACString p_field17);
  void executeP0088();
  void executeP0089(in AString p_key);
  void executeP008A(in AString p_target);
  void executeP008B(in AString p_target);
  void executeP008C(in AString p_target);
  void executeP008D(in AString p_target);
  void executeP008E(in AString p_target);
  void executeP008F(in AString p_target);
  void executeP0090(in AString p_key);
  void executeP0091(in AString p_key);
  void executeP0092(in AString p_key);
  void executeP0093(in AString p_key);
  void executeP0094(in AString p_key);
  void executeP0095(in AString p_key);
  void executeP0096(in AString p_key);
  void executeP0097(in AString p_key);
  void executeP0098(in ACString p_search);
  void executeP0099(in ACString p_search);
  void executeP009A(in AString p_key);
  void executeP009B(in ACString p_search);
  void executeP009C(in ACString p_search);
  void executeP009D(in AString p_key);
  void executeP009E(in AString p_key);
  void executeP009F(in AString p_key, in ACString p_field1, in ACString p_field2, in ACString p_field3, in ACString p_field4, in ACString p_field5, in ACString p_field6, in ACString p_field7);
  void executeP00A0(in ACString p_search);
  void executeP00A1(in ACString p_search);
  void executeP00A2(in AString p_key);
  void executeP00A3(in ACString p_search);
  void executeP00A4(in ACString p_search);
  void executeP00A5(in AString p_key);
  void executeP00A6(in AString p_key, in ACString p_field1, in ACString p_field2, in ACString p_field3, in ACString p_field4, in ACString p_field5, in ACString p_field6, in ACString p_field7);
  void executeP00A7();
  void executeP00A8(in AString p_key);
  void executeP00A9(in AString p_key);
  void executeP00AA(in AString p_key);
  void executeP00AB(in AString p_key);
  void executeP00AC(in AString p_key);
  void executeP00AD(in AString p_key);
  void executeP00AE(in AString p_key);
  void executeP00AF(in AString p_key);
  void executeP00B0(in AString p_key);
  void executeP00B1(in AString p_key);
  void executeP00B2(in AString p_key);
  void executeP00B3(in AString p_key);
  void executeP00B4(in AString p_key);
  void executeP00B5(in AString p_key);
  void executeP00B6(in AString p_key);
  void executeP00B7(in AString p_key);
  void executeP00B8(in AString p_key);
  void executeP00B9(in ACString p_search);
  void executeP00BA(in ACString p_search);
  void executeP00BB(in AString p_key);
  void executeP00BC(in ACString p_search);
  void executeP00BD(in ACString p_search);
  void executeP00BE(in AString p_key);
  void executeP00BF(in ACString p_search);
  void executeP00C0(in ACString p_search);
  void executeP00C1(in AString p_key);
  void executeP00C2(in ACString p_search);
  void executeP00C3(in ACString p_search);
  void executeP00C4(in AString p_key);
  void executeP00C5(in AString p_key);
  void executeP00C6(in AString p_key, in ACString p_field1, in ACString p_field2, in ACString p_field3, in ACString p_field4, in ACString p_field5, in ACString p_field6, in ACString p_field7, in ACString p_field8, in ACString p_field9, in ACString p_field10, in ACString p_field11, in ACString p_field12, in ACString p_field13);
  void executeP00C7(in ACString p_search);
  void executeP00C8(in ACString p_search);
  void executeP00C9(in AString p_key);
  void executeP00CA(in ACString p_search);
  void executeP00CB(in ACString p_search);
  void executeP00CC(in AString p_key);
  void executeP00CD(in ACString p_search);
  void executeP00CE(in ACString p_search);
  void executeP00CF(in AString p_key);
  void executeP00D0(in ACString p_search);
  void executeP00D1(in ACString p_search);
  void executeP00D2(in AString p_key);
  void executeP00D3(in AString p_key, in ACString p_field1, in ACString p_field2, in ACString p_field3, in ACString p_field4, in ACString p_field5, in ACString p_field6, in ACString p_field7, in ACString p_field8, in ACString p_field9, in ACString p_field10, in ACString p_field11, in ACString p_field12, in ACString p_field13);
  void executeP00D4();
  void executeP00D5(in AString p_key);
  void executeP00D6(in AString p_target);
  void executeP00D7(in AString p_target);
  void executeP00D8(in AString p_target);
  void executeP00D9(in AString p_target);
  void executeP00DA(in AString p_target);
  void executeP00DB(in AString p_target);
  void executeP00DC(in AString p_target);
  void executeP00DD(in AString p_target);

};

%{C++

// {f9f273c2-1d30-4cf1-9921-7ad7c98487f4}
#define MOZ_C02GESTSEA_CID { 0xf9f273c2, 0x1d30, 0x4cf1, { 0x99, 0x21, 0x7a, 0xd7, 0xc9, 0x84, 0x87, 0xf4 } }
#define MOZ_C02GESTSEA_CONTRACTID "@brice.fr/gestsea/C02gestsea;1"
#define MOZ_C02GESTSEA_CLASSNAME "C02gestsea"

%}
